'use strict';
const {Game,N}=TankGuard,g=new Game(),canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),S=canvas.width/N;
const $=s=>document.querySelector(s),held=new Map(),keys=new Map();let prev=performance.now(),tapDir,dirUntil=0,fireUntil=0;
function clear(){held.clear();keys.clear();tapDir=undefined;dirUntil=0;fireUntil=0;}
function pause(){g.pause();clear();}
$('#pause').onclick=pause;$('#primary').onclick=()=>{if(g.state==='ready')g.start();else if(g.state==='paused')g.pause();else if(g.state==='stageclear')g.next();else{g.reset();g.start();}clear();};$('#restart').onclick=()=>{g.reset();clear();};
const dirKeys={ArrowUp:0,w:0,ArrowRight:1,d:1,ArrowDown:2,s:2,ArrowLeft:3,a:3};
addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(k in dirKeys||k===' ')e.preventDefault();if(!e.repeat){if(k==='p'||k==='Escape')pause();if(k==='r'&&['paused','lost','won','stageclear'].includes(g.state)){g.reset();clear();}}if(k in dirKeys){keys.set(k,dirKeys[k]);tapDir=dirKeys[k];dirUntil=performance.now()+140;}if(k===' '){keys.set(k,'fire');fireUntil=performance.now()+60;}});
addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));
for(const b of document.querySelectorAll('[data-dir],#fire')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,b.id==='fire'?'fire':+b.dataset.dir);if(b.id==='fire')fireUntil=performance.now()+60;else{tapDir=+b.dataset.dir;dirUntil=performance.now()+140;}});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,e=>held.delete(e.pointerId));b.addEventListener('contextmenu',e=>e.preventDefault());}
function suspend(){clear();if(g.state==='playing')g.pause();}addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});
function tank(e,color){ctx.save();ctx.translate((e.x+.5)*S,(e.y+.5)*S);ctx.rotate(e.dir*Math.PI/2);ctx.fillStyle='#0d211b';ctx.fillRect(-S*.4,-S*.38,S*.2,S*.76);ctx.fillRect(S*.2,-S*.38,S*.2,S*.76);ctx.fillStyle=color;ctx.fillRect(-S*.25,-S*.3,S*.5,S*.6);ctx.fillStyle='#ffffff55';ctx.fillRect(-S*.12,-S*.15,S*.24,S*.3);ctx.fillStyle=color;ctx.fillRect(-S*.07,-S*.53,S*.14,S*.42);ctx.restore();}
function draw(){ctx.fillStyle='#152d25';ctx.fillRect(0,0,720,720);for(let y=0;y<N;y++)for(let x=0;x<N;x++){const t=g.map[y][x],px=x*S,py=y*S;ctx.strokeStyle='#ffffff05';ctx.strokeRect(px,py,S,S);if(t==='B'){ctx.fillStyle='#a97651';ctx.fillRect(px+2,py+2,S-4,S-4);ctx.strokeStyle='#684c38';ctx.beginPath();ctx.moveTo(px,py+S/2);ctx.lineTo(px+S,py+S/2);ctx.moveTo(px+S/2,py);ctx.lineTo(px+S/2,py+S/2);ctx.moveTo(px+S/4,py+S/2);ctx.lineTo(px+S/4,py+S);ctx.stroke();}if(t==='S'){ctx.fillStyle='#819994';ctx.fillRect(px+2,py+2,S-4,S-4);ctx.strokeStyle='#b5c8be';ctx.strokeRect(px+7,py+7,S-14,S-14);}}
ctx.fillStyle=g.base.alive?'#efd078':'#6b5148';ctx.beginPath();ctx.moveTo(7.5*S,14.12*S);ctx.lineTo(7.87*S,14.3*S);ctx.lineTo(7.8*S,14.72*S);ctx.lineTo(7.5*S,14.94*S);ctx.lineTo(7.2*S,14.72*S);ctx.lineTo(7.13*S,14.3*S);ctx.closePath();ctx.fill();ctx.fillStyle='#213c30';ctx.font='bold 22px system-ui';ctx.textAlign='center';ctx.fillText('守',7.5*S,14.66*S);
for(const e of g.enemies)tank(e,'#ed8261');tank(g.player,'#76dfab');if(g.player.immune>0){ctx.strokeStyle='#b9f9d3';ctx.lineWidth=2;ctx.beginPath();ctx.arc((g.player.x+.5)*S,(g.player.y+.5)*S,S*.48,0,Math.PI*2);ctx.stroke();}
for(const b of g.bullets){ctx.fillStyle=b.team==='player'?'#d4ffdf':'#ff987a';ctx.beginPath();ctx.arc(b.x*S,b.y*S,b.team==='player'?4:6,0,Math.PI*2);ctx.fill();}for(const e of g.effects){ctx.strokeStyle='#efd078';ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x*S,e.y*S,S*(.55-e.t),0,Math.PI*2);ctx.stroke();}
$('#stage').textContent=`0${g.stage+1} / 03`;$('#lives').textContent=g.lives;$('#score').textContent=g.score/100;$('#pause').disabled=!['playing','paused'].includes(g.state);$('#pause').textContent=g.state==='paused'?'계속하기':'일시정지';$('#overlay').hidden=g.state==='playing';$('#restart').hidden=!['paused','stageclear'].includes(g.state);
const states={ready:['마지막 기지를 지켜라','벽돌은 부술 수 있지만 강철벽은 남습니다. 적 탱크를 모두 막아 세 번의 작전을 마치세요.','작전 시작'],paused:['잠시 정지','이동과 발사를 멈췄습니다. 준비되면 계속하세요.','계속하기'],stageclear:['기지를 지켰습니다',`작전 ${g.stage+1} 완료. 다음 작전에서는 벽 배치와 적의 수가 달라집니다.`,'다음 작전'],lost:['방어 실패',g.reason+' 길을 너무 열지는 않았나요?','다시 도전'],won:['세 번의 작전 완료',`${g.score/100}대 격파. 마지막 기지가 살아남았습니다.`,'다시 도전']};if(states[g.state]){const a=states[g.state];$('#message').textContent=a[0];$('#description').textContent=a[1];$('#primary').textContent=a[2];}}
function frame(t){const values=[...keys.values(),...held.values()],dirs=values.filter(Number.isInteger);g.step((t-prev)/1000,{dir:dirs.at(-1)??(t<dirUntil?tapDir:undefined),fire:values.includes('fire')||t<fireUntil});prev=t;draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
