'use strict';
const E=Sokoban,$=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');let level=0,state;
E.levels.forEach((l,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`0${i+1} / ${l.name}`;$('level').append(o)});
function start(i){level=i;state=E.create(E.levels[i].map);$('level').value=i;render();}
function tile(x,y,size,fill,inset=2){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x*size+inset,y*size+inset,size-inset*2,size-inset*2,7);ctx.fill();}
function render(){const size=80;canvas.width=state.width*size;canvas.height=state.height*size;canvas.style.aspectRatio=`${state.width}/${state.height}`;ctx.fillStyle='#163f38';ctx.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<state.height;y++)for(let x=0;x<state.width;x++){const p=`${x},${y}`;tile(x,y,size,state.walls.includes(p)?'#36574b':'#dce1c8');if(state.walls.includes(p)){ctx.fillStyle='#456657';ctx.fillRect(x*size+10,y*size+11,size-20,4);}if(state.goals.includes(p)){ctx.strokeStyle='#4f937a';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x*size+40,y*size+40,18,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#78ab8c';ctx.beginPath();ctx.arc(x*size+40,y*size+40,6,0,Math.PI*2);ctx.fill();}}
const trapped=E.corners(state);state.boxes.forEach(p=>{let[x,y]=p.split(',').map(Number);tile(x,y,size,state.goals.includes(p)?'#5a997b':'#dba855',12);ctx.strokeStyle=state.goals.includes(p)?'#c8e3be':'#9c7037';ctx.lineWidth=5;ctx.strokeRect(x*size+21,y*size+21,38,38);ctx.beginPath();ctx.moveTo(x*size+22,y*size+22);ctx.lineTo(x*size+58,y*size+58);ctx.stroke();if(trapped.includes(p)){ctx.strokeStyle='#be533a';ctx.lineWidth=5;ctx.strokeRect(x*size+9,y*size+9,62,62);}});let[px,py]=state.player.split(',').map(Number);ctx.fillStyle='#233f3a33';ctx.beginPath();ctx.ellipse(px*80+40,py*80+55,24,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ef7950';ctx.beginPath();ctx.arc(px*80+40,py*80+39,23,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff3d3';ctx.beginPath();ctx.arc(px*80+40,py*80+32,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#173f38';ctx.fillRect(px*80+33,py*80+30,4,4);ctx.fillRect(px*80+43,py*80+30,4,4);
$('moves').textContent=state.moves;$('pushes').textContent=state.pushes;$('goals').textContent=`${state.boxes.filter(p=>state.goals.includes(p)).length} / ${state.goals.length}`;$('undo').disabled=!state.history.length;$('next').hidden=!E.won(state)||level===E.levels.length-1;$('message').textContent=E.won(state)?(level===E.levels.length-1?'마지막 창고까지 정리 끝! 다른 길로 더 적게 움직여 보세요.':'정리 끝! 다음 창고로 가거나 한 수 되돌려 볼 수 있어요.'):trapped.length?'상자가 구석에 갇혔어요. Z 또는 ‘한 수 되돌리기’로 돌아가세요.':'초록 점 위로 상자를 밀어 주세요. 옆이나 뒤로 돌아가는 길도 살펴보세요.';canvas.setAttribute('aria-label',`창고 ${level+1}. 이동 ${state.moves}, 밀기 ${state.pushes}, 도착 ${$('goals').textContent}. ${$('message').textContent}`);}
function step(dx,dy){E.move(state,dx,dy);render();}
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>step(...b.dataset.dir.split(',').map(Number)));$('undo').onclick=()=>{E.undo(state);render()};$('restart').onclick=()=>start(level);$('next').onclick=()=>start(Math.min(level+1,E.levels.length-1));$('level').onchange=e=>start(Number(e.target.value));document.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT'||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase(),dirs={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(dirs[k]){e.preventDefault();step(...dirs[k]);}else if(k==='z'){e.preventDefault();E.undo(state);render();}else if(k==='r'){e.preventDefault();start(level);}});start(0);
