const game=new LineGarden(),canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},keys={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};let held=null,repeat=0,last=0;
function clear(){held=null;repeat=0;}
function begin(dir){if(game.state!=='playing')return;held=dir;repeat=0;game.move(...dirs[dir]);}
function pause(){clear();if(game.state==='playing')game.pause();else if(game.state==='paused')game.start();}
$('mainBtn').onclick=()=>{clear();if(['lost','won'].includes(game.state))game.reset();game.start();};$('pause').onclick=pause;$('reset').onclick=()=>{clear();game.reset();};
window.addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON'&&(e.key===' '||e.key==='Enter'))return;if(keys[e.key]){e.preventDefault();if(!e.repeat)begin(keys[e.key]);}else if([' ','p','P','Escape'].includes(e.key)){e.preventDefault();if(!e.repeat)pause();}});window.addEventListener('keyup',e=>{if(keys[e.key]===held)clear();});
for(const b of document.querySelectorAll('[data-dir]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);begin(b.dataset.dir);};b.onpointerup=clear;b.onpointercancel=clear;b.onlostpointercapture=clear;}
window.addEventListener('blur',()=>{clear();game.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clear();game.pause();}});
function draw(){const s=28;ctx.fillStyle='#183c36';ctx.fillRect(0,0,784,672);for(let y=0;y<game.rows;y++)for(let x=0;x<game.cols;x++){const v=game.grid[y][x];ctx.fillStyle=v===1?'#a8c7a0':v===2?'#efc56b':'#1c443c';ctx.fillRect(x*s+1,y*s+1,s-2,s-2);if(v===1){ctx.fillStyle='#93b78d';ctx.fillRect(x*s+12,y*s+12,3,3);}}
 for(const e of game.enemies){ctx.save();ctx.translate(e.x*s+14,e.y*s+14);ctx.fillStyle='#ee8972';ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#542f2c';ctx.fillRect(-5,-3,3,3);ctx.fillRect(2,-3,3,3);ctx.restore();}ctx.fillStyle='#fff8e4';ctx.strokeStyle='#315e49';ctx.lineWidth=3;ctx.beginPath();ctx.arc(game.player.x*s+14,game.player.y*s+14,10,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#315e49';ctx.fillRect(game.player.x*s+11,game.player.y*s+11,6,6);
 $('area').textContent=game.percent().toFixed(1)+'%';$('progress').style.width=Math.min(100,game.percent()/game.goal*100)+'%';$('lives').textContent='● '.repeat(game.lives)+'○ '.repeat(3-game.lives);$('time').textContent=String(Math.floor(game.elapsed/60)).padStart(2,'0')+':'+String(Math.floor(game.elapsed%60)).padStart(2,'0');$('message').textContent=game.message;$('pause').textContent=game.state==='paused'?'계속하기':'일시정지';$('pause').disabled=!['playing','paused'].includes(game.state);$('veil').hidden=game.state==='playing';if(game.state==='ready'){ $('heading').textContent='선을 잇고, 내 땅으로.';$('desc').innerHTML='테두리는 안전한 땅입니다.<br>선을 그어 다시 연결하면 영역을 얻습니다.<br>붉은 벌레가 선을 건드리기 전에 돌아오세요.';$('mainBtn').textContent='시작하기';}else if(game.state==='paused'){$('heading').textContent='잠깐, 숨 고르기';$('desc').textContent='다음에 그을 선을 생각해 보세요. 이어서 같은 자리에서 시작합니다.';$('mainBtn').textContent='계속하기';}else if(game.state==='won'||game.state==='lost'){$('heading').textContent=game.state==='won'?'정원이 넓어졌습니다!':'이번 정원은 여기까지';$('desc').textContent=`확보한 땅 ${game.percent().toFixed(1)}% · 완성한 선 ${game.captures}개 · ${Math.floor(game.elapsed)}초`;$('mainBtn').textContent='다시 도전';}}
function frame(t){const dt=Math.min((t-last)/1000||0,.1);last=t;if(held&&game.state==='playing'){repeat+=dt;while(repeat>=.105){game.move(...dirs[held]);repeat-=.105;}}game.tick(dt);draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
