const {test}=require('node:test');
const a=require('node:assert/strict');
const E=require('./engine.js');
function fixture(){const s=E.createState();s.board=Array.from({length:10},()=>Array(9).fill(null));s.turn='cho';s.result=null;s.started=true;s.board[8][4]={side:'cho',type:'K'};s.board[1][3]={side:'han',type:'K'};return s;}
function put(s,r,c,type,side='cho'){s.board[r][c]={side,type};return s;}
function has(ms,r,c){return ms.some(m=>m.r===r&&m.c===c);}
test('initial board contains 16 pieces per side; Cho plays first',()=>{const s=E.createState();for(const side of ['cho','han'])a.equal(s.board.flat().filter(p=>p?.side===side).length,16);a.equal(s.turn,'cho');});
test('horse blocked at orthogonal leg, not the diagonal neighbour',()=>{const s=fixture();put(s,5,4,'H');a.ok(has(E.pseudoMoves(s,5,4),3,3));put(s,4,4,'P');a.ok(!has(E.pseudoMoves(s,5,4),3,3));a.ok(!has(E.pseudoMoves(s,5,4),3,5));a.ok(has(E.pseudoMoves(s,5,4),4,2));});
test('elephant is blocked on each of two intermediate points',()=>{const s=fixture();put(s,5,4,'E');a.ok(has(E.pseudoMoves(s,5,4),2,2));put(s,4,4,'P');a.ok(!has(E.pseudoMoves(s,5,4),2,2));s.board[4][4]=null;put(s,3,3,'P');a.ok(!has(E.pseudoMoves(s,5,4),2,2));s.board[3][3]=null;a.ok(has(E.pseudoMoves(s,5,4),2,2));});
test('cannon cannot move without a screen; one screen permits empty moves and capture',()=>{const s=fixture();put(s,5,0,'C');a.ok(!has(E.pseudoMoves(s,5,0),5,1));put(s,5,2,'P');put(s,5,6,'R','han');const ms=E.pseudoMoves(s,5,0);a.ok(has(ms,5,3));a.ok(has(ms,5,6));a.ok(!has(ms,5,7));a.ok(!has(ms,5,2));});
test('cannon cannot screen with cannon or capture cannon',()=>{const s=fixture();put(s,5,0,'C');put(s,5,2,'C');a.ok(!has(E.pseudoMoves(s,5,0),5,3));put(s,5,2,'P');put(s,5,6,'C','han');a.ok(has(E.pseudoMoves(s,5,0),5,5));a.ok(!has(E.pseudoMoves(s,5,0),5,6));a.ok(!has(E.pseudoMoves(s,5,0),5,7));});
test('palace rook diagonals must follow drawn lines',()=>{const s=fixture();put(s,0,3,'R');s.board[1][3]=null;put(s,1,5,'K','han');a.ok(has(E.pseudoMoves(s,0,3),2,5));put(s,1,4,'P');a.ok(!has(E.pseudoMoves(s,0,3),2,5));});
test('palace cannon jumps center to opposite corner only',()=>{const s=fixture();put(s,0,3,'C');s.board[1][3]=null;put(s,1,5,'K','han');a.ok(!has(E.pseudoMoves(s,0,3),2,5));put(s,1,4,'P');a.ok(has(E.pseudoMoves(s,0,3),2,5));put(s,1,4,'C');a.ok(!has(E.pseudoMoves(s,0,3),2,5));});
test('king and advisor cannot leave own palace or use nonexistent diagonals',()=>{const s=fixture();s.board[8][4]=null;put(s,9,4,'K');put(s,7,3,'A');a.ok(has(E.pseudoMoves(s,7,3),8,4));a.ok(!has(E.pseudoMoves(s,7,3),6,3));put(s,7,4,'A');a.ok(!has(E.pseudoMoves(s,7,4),8,3));});
test('soldier has sideways and forward but no backward; palace forward diagonals',()=>{const s=fixture();put(s,2,3,'P');const ms=E.pseudoMoves(s,2,3);a.ok(has(ms,1,4));a.ok(has(ms,2,2));a.ok(!has(ms,3,3));put(s,1,4,'P');a.ok(has(E.pseudoMoves(s,1,4),0,3));a.ok(!has(E.pseudoMoves(s,1,4),2,3));});
test('facing kings is bikjang, not check',()=>{const s=fixture();s.board[1][3]=null;put(s,1,4,'K','han');a.equal(E.kingsFace(s),true);a.equal(E.isCheck(s,'cho'),false);a.equal(E.isCheck(s,'han'),false);});
test('self-check moves forbidden and pass forbidden in check',()=>{const s=fixture();put(s,4,4,'R','han');put(s,6,4,'R');a.ok(!has(E.legalMoves(s,6,4),6,5));s.board[6][4]=null;a.equal(E.isCheck(s,'cho'),true);a.equal(E.pass(s),false);});
test('king square attacked by a rook is detected even though king capture is forbidden',()=>{const s=fixture();put(s,4,4,'R','han');a.ok(E.isCheck(s,'cho'));a.ok(!has(E.legalMoves(s,8,4),7,4));});
test('move and undo restore captures and turn',()=>{const s=fixture();put(s,5,0,'R');put(s,5,2,'P','han');const before=JSON.stringify(s.board);a.equal(E.move(s,5,0,5,2),true);a.equal(s.turn,'han');a.equal(E.undo(s),true);a.equal(JSON.stringify(s.board),before);a.equal(s.turn,'cho');});
test('two normal passes draw; undo reopens play',()=>{const s=fixture();a.equal(E.pass(s),true);a.equal(E.pass(s),true);a.ok(s.result);a.equal(E.move(s,8,4,8,5),false);a.equal(E.undo(s),true);a.equal(s.result,null);});

test('four placement combinations preserve each army and lock after first action',()=>{for(const l of ['HE','EH'])for(const r of ['HE','EH']){const s=E.createState();a.equal(E.setSetup(s,'cho',l,r),true);a.equal(s.board[9][1].type,l[0]);a.equal(s.board[9][7].type,r[1]);a.equal(E.pass(s),true);a.equal(E.setSetup(s,'cho','HE','EH'),false);}});
test('bikjang response must break facing, or may accept draw even in check',()=>{const s=fixture();s.board[1][3]=null;put(s,1,4,'K','han');put(s,5,0,'R');a.equal(E.move(s,5,0,5,1),false);a.ok(has(E.legalMoves(s,8,4),8,5));put(s,8,0,'R','han');a.equal(E.isCheck(s,'cho'),true);a.equal(E.bikjangDraw(s),true);a.equal(s.result.reason,'bikjang');a.equal(E.undo(s),true);a.equal(s.result,null);});
test('checkmate ends without capturing king, undo restores',()=>{const s=fixture();s.board[1][3]=null;put(s,1,4,'K','han');s.board[8][4]=null;put(s,8,3,'K');put(s,3,3,'R');put(s,3,5,'R');put(s,4,4,'R');a.equal(E.move(s,4,4,3,4),true);a.equal(s.result?.reason,'checkmate');a.equal(s.result?.winner,'cho');a.equal(s.board[1][4].type,'K');a.equal(E.undo(s),true);a.equal(s.result,null);});
test('resignation and agreement are undoable and block play',()=>{const s=E.createState();a.equal(E.resign(s),true);a.equal(s.result.winner,'han');a.equal(E.pass(s),false);a.equal(E.undo(s),true);a.equal(s.result,null);a.equal(E.agreeDraw(s),true);a.equal(s.result.reason,'agreement');});
