'use strict';const E=SkyShield,$=id=>document.getElementById(id),c=$('game'),ctx=c.getContext('2d');let s=E.create(),prev=performance.now();
function round(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function draw(){ctx.fillStyle='#17332e';ctx.fillRect(0,0,640,480);for(let i=0;i<38;i++){ctx.fillStyle=i%2?'#8faaa088':'#c2ceba77';ctx.fillRect((i*137+43)%640,(i*73+17)%350,2,2);}ctx.fillStyle='#244239';ctx.beginPath();ctx.moveTo(0,390);for(let x=0;x<=640;x+=40)ctx.lineTo(x,365+30*Math.sin(x*.017));ctx.lineTo(640,480);ctx.lineTo(0,480);ctx.fill();ctx.fillStyle='#537262';ctx.fillRect(0,422,640,58);for(let i=0;i<3;i++){let x=E.BASES[i];if(s.bases[i]){round(x-26,402,52,27,5,'#c7b887');round(x-18,387,36,19,4,'#dfd7b6');ctx.fillStyle='#f1bc62';for(let j=0;j<3;j++)ctx.fillRect(x-14+j*11,410,5,8);}else{round(x-26,417,52,12,3,'#314b40');ctx.fillStyle='#789383';ctx.fillRect(x-12,410,14,7);}}round(298,408,44,22,5,'#f19b59');ctx.strokeStyle='#f8ca79';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(320,413);let a=s.aim?Math.atan2(s.aim.y-420,s.aim.x-320):-Math.PI/2;ctx.lineTo(320+Math.cos(a)*26,413+Math.sin(a)*26);ctx.stroke();
for(const e of s.enemies){ctx.strokeStyle='#edaa6a99';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(e.fromX,0);ctx.lineTo(e.x,e.y);ctx.stroke();ctx.fillStyle='#ffcc82';ctx.beginPath();ctx.arc(e.x,e.y,4,0,Math.PI*2);ctx.fill();}
for(const a of s.shots){ctx.strokeStyle='#8dcdd9';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(320,420);ctx.lineTo(a.x,a.y);ctx.stroke();ctx.fillStyle='#d4f4e6';ctx.beginPath();ctx.arc(a.x,a.y,3,0,Math.PI*2);ctx.fill();}
for(const b of s.bursts){let r=E.radius(b);ctx.fillStyle=b.max===32?'#f8d79355':'#88d6c744';ctx.strokeStyle=b.max===32?'#e8c574':'#aadfd0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();}if(s.aim){ctx.strokeStyle='#b4dfc5';ctx.lineWidth=1;ctx.beginPath();ctx.arc(s.aim.x,s.aim.y,8,0,Math.PI*2);ctx.moveTo(s.aim.x-13,s.aim.y);ctx.lineTo(s.aim.x+13,s.aim.y);ctx.moveTo(s.aim.x,s.aim.y-13);ctx.lineTo(s.aim.x,s.aim.y+13);ctx.stroke();}
ctx.fillStyle='#bbceba';ctx.font='12px system-ui';ctx.textAlign='left';ctx.fillText('SKY SHIELD',18,25);ctx.textAlign='right';ctx.fillText(s.time.toFixed(1)+' s',621,25);
if(s.mode!=='playing'){round(155,144,330,133,12,'#e8eddded');ctx.textAlign='center';ctx.fillStyle='#294f3d';ctx.font='bold 24px system-ui';ctx.fillText({ready:'먼저 도착할 빛',paused:'잠깐 멈춤',clear:s.wave===3?'세 차례 방어 완료':'이번 하늘을 지켰습니다',over:'다시 조준해 볼까요?'}[s.mode],320,187);ctx.font='14px system-ui';ctx.fillText(s.mode==='ready'?'현재 위치보다 조금 앞을 보세요':`${s.hit}발 방어 · ${s.score}점`,320,218);ctx.fillText(s.mode==='paused'?'P 또는 계속 방어':s.mode==='clear'&&s.wave<3?'다음 차례에서 이어집니다':'아래 버튼으로 시작',320,245);}
$('wave').textContent=s.wave+' / 3';$('bases').textContent=s.bases.filter(Boolean).length+'곳';$('ammo').textContent=s.ammo+'발';$('score').textContent=s.score+'점';$('hit').textContent=s.hit+'발';$('message').textContent=s.message+(s.mode==='playing'&&s.ammo===0?' 방어탄을 모두 사용했습니다.':'');$('start').textContent=s.mode==='ready'?'방어 시작':'처음부터';$('pause').textContent=s.mode==='paused'?'계속 방어':'일시정지';$('pause').disabled=!['playing','paused'].includes(s.mode);$('next').disabled=s.mode!=='clear'||s.wave>=3;for(const id of ['left','center','right'])$(id).disabled=s.mode!=='playing'||s.ammo<=0;c.setAttribute('aria-label',`미사일 방어 게임, 상태 ${s.mode}, 차례 ${s.wave}, 시간 ${s.time.toFixed(1)}, 기지 ${s.bases.filter(Boolean).length}, 탄 ${s.ammo}, 점수 ${s.score}, 방어 ${s.hit}, 유실 ${s.missed}, 방어탄비행 ${s.shots.length}, 폭발 ${s.bursts.length}, 미사일 `+s.enemies.map(e=>`x${Math.round(e.x)} y${Math.round(e.y)}`).join('; '));}
function pause(){if(s.mode==='playing'){s.mode='paused';s.message='시간과 비행 궤적을 멈췄습니다.';}else if(s.mode==='paused'){s.mode='playing';s.message='방어를 이어갑니다.';}draw();}
$('start').onclick=()=>{s=E.create();E.start(s);draw();};$('pause').onclick=pause;$('next').onclick=()=>{E.next(s);draw();};['left','center','right'].forEach((id,i)=>$(id).onclick=()=>{E.fire(s,E.BASES[i],250);draw();});c.addEventListener('pointerdown',e=>{const r=c.getBoundingClientRect();const scale=Math.min(r.width/640,r.height/480),ox=(r.width-640*scale)/2,oy=(r.height-480*scale)/2,x=(e.clientX-r.left-ox)/scale,y=(e.clientY-r.top-oy)/scale;if(x<0||x>640||y<0||y>480)return;E.fire(s,x,y);draw();});window.addEventListener('keydown',e=>{if(['1','2','3','p','P'].includes(e.key)){e.preventDefault();if(e.repeat)return;if(e.key.toLowerCase()==='p')pause();else E.fire(s,E.BASES[Number(e.key)-1],250);draw();}});window.addEventListener('blur',()=>{if(s.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.mode==='playing')pause();});function loop(now){E.step(s,Math.min((now-prev)/1000,.05));prev=now;draw();requestAnimationFrame(loop);}draw();requestAnimationFrame(loop);
