'use strict';const E=SnowRoll,$=id=>document.getElementById(id),canvas=$('game'),g=canvas.getContext('2d');let s=E.create(),keys={},walk=0,last=0,acc=0,msg='';
function stop(){keys={};walk=0}
function sync(){$('stage').textContent=`${s.stage+1} / 3`;$('fruit').textContent=`${s.defeated} / ${s.enemies.length}`;$('score').textContent=s.score;$('lives').textContent=s.lives;$('start').hidden=!['ready','clear'].includes(s.status)||s.status==='clear'&&s.stage===2;$('start').textContent=s.status==='clear'?'다음 눈길 →':'시작';$('pause').disabled=!['playing','paused'].includes(s.status);$('pause').textContent=s.status==='paused'?'계속':'일시정지';$('left').setAttribute('aria-pressed',walk===-1);$('right').setAttribute('aria-pressed',walk===1);let text=s.status==='ready'?'눈을 네 번 맞히고, 가까이에서 눈덩이를 밀어 보세요.':s.status==='paused'?'잠깐 멈췄습니다. 눈이 녹는 시간도 멈춥니다.':s.status==='over'?'기회를 모두 썼어요. 처음부터 다시 도전해 보세요.':s.message;if(msg!==text){msg=text;$('status').textContent=text}canvas.setAttribute('aria-label',`눈길 ${s.stage+1}, 격파 ${s.defeated}/${s.enemies.length}, 점수 ${s.score}, 기회 ${s.lives}, 위치 ${Math.round(s.player.x)}, 높이 ${Math.round(s.player.y)}, 눈덩이 ${s.enemies.filter(e=>e.state==='frozen').length}, 굴러가는 공 ${s.enemies.filter(e=>e.state==='rolling').length}, 최고 연쇄 ${s.bestChain}. ${text}`)}
function oval(x,y,rx,ry,c){g.fillStyle=c;g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fill()}
function draw(){g.fillStyle='#202d49';g.fillRect(0,0,800,480);g.fillStyle='#314461';for(let x=0;x<800;x+=80){g.fillRect(x,0,2,480)}g.fillStyle='#8babc0';g.font='12px system-ui';g.textAlign='left';g.fillText(E.levels[s.stage].name,22,30);for(let f of[{x:0,y:E.FLOOR,w:800},...E.levels[s.stage].shelves]){g.fillStyle='#5a759a';g.fillRect(f.x,f.y,f.w,18);g.fillStyle='#c1d5e2';g.fillRect(f.x,f.y,f.w,5)}
for(let q of s.shots)oval(q.x,q.y,6,6,'#f1f6ed');for(let e of s.enemies){if(e.state==='gone')continue;if(e.state==='frozen'||e.state==='rolling'){oval(e.x,e.y-20,23,23,'#e2edf1');oval(e.x-7,e.y-27,8,5,'#ffffff');g.strokeStyle='#a3bdcc';g.lineWidth=2;g.beginPath();g.arc(e.x,e.y-20,17,s.time*3,s.time*3+2);g.stroke();if(e.state==='frozen'){g.fillStyle='#efc283';g.fillRect(e.x-22,e.y-49,44*e.thaw/8,3)}}else{oval(e.x,e.y-16,16,18,['#b3a4da','#8bc7c4','#db9ea9'][e.id%3]);oval(e.x-6,e.y-35,5,8,'#dfbdab');oval(e.x+6,e.y-35,5,8,'#dfbdab');oval(e.x-5,e.y-19,2,3,'#193247');oval(e.x+5,e.y-19,2,3,'#193247');if(e.snow){g.fillStyle='#e9f3f3';g.fillRect(e.x-16,e.y-12,32,e.snow*4);g.fillStyle='#eee1be';g.font='11px system-ui';g.textAlign='center';g.fillText(`${e.snow}/4`,e.x,e.y-44)}}}
let p=s.player;g.save();g.globalAlpha=s.invincible>0&&Math.floor(s.time*8)%2===0?.45:1;oval(p.x,p.y-16,14,17,'#e0a36d');oval(p.x,p.y-35,13,13,'#fff0d4');oval(p.x,p.y-42,16,8,'#dc8654');g.fillStyle='#784954';g.fillRect(p.x-12,p.y-26,24,5);oval(p.x-5,p.y-35,2,2,'#263a52');oval(p.x+5,p.y-35,2,2,'#263a52');g.restore();if(s.status!=='playing'){g.fillStyle='#111a2caa';g.fillRect(0,0,800,480);g.textAlign='center';g.fillStyle='#fff0d1';g.font='bold 30px system-ui';g.fillText({ready:'눈덩이 하나로 어디까지?',paused:'잠깐 쉬어가기',clear:s.stage===2?'모두 굴렸어요!':'눈길 정리 완료',over:'다시 한 바퀴?'}[s.status],400,215);g.font='16px system-ui';g.fillStyle='#c4d9df';g.fillText(`격파 ${s.defeated}/${s.enemies.length} · 점수 ${s.score} · 최고 ${s.bestChain}연쇄`,400,253)}}
function pause(){if(s.status==='playing'){s.status='paused';stop()}else if(s.status==='paused')s.status='playing';sync()}
$('start').onclick=()=>{if(s.status==='clear')s=E.create(s.stage+1,s.score,s.lives);stop();E.start(s);sync()};$('pause').onclick=pause;$('restart').onclick=()=>{s=E.create();stop();sync()};$('left').onclick=()=>walk=walk===-1?0:-1;$('right').onclick=()=>walk=walk===1?0:1;$('stop').onclick=stop;$('jump').onclick=()=>E.jump(s);$('shoot').onclick=()=>{E.fire(s);sync()};$('push').onclick=()=>{E.push(s);sync()};
document.addEventListener('keydown',e=>{if(e.metaKey||e.ctrlKey||e.altKey)return;let k=e.key.toLowerCase();if(['arrowleft','arrowright','a','d',' ','z','x'].includes(k))e.preventDefault();if(['arrowleft','a'].includes(k)){keys.left=true;walk=0}if(['arrowright','d'].includes(k)){keys.right=true;walk=0}if(k==='z'){E.fire(s);keys.fire=true}if(!e.repeat){if(k===' ')E.jump(s);if(k==='x')E.push(s);if(k==='p')pause()}});document.addEventListener('keyup',e=>{let k=e.key.toLowerCase();if(['arrowleft','a'].includes(k))keys.left=false;if(['arrowright','d'].includes(k))keys.right=false;if(k==='z')keys.fire=false});window.addEventListener('blur',()=>{stop();if(s.status==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();if(s.status==='playing')pause()}});
function frame(t){let dt=last?Math.min((t-last)/1000,.1):0;last=t;if(s.status==='playing'){acc+=dt;while(acc>=1/120){let life=s.lives;if(keys.fire)E.fire(s);E.step(s,1/120,{left:keys.left||walk===-1,right:keys.right||walk===1});if(life>s.lives)stop();acc-=1/120}}else acc=0;sync();draw();requestAnimationFrame(frame)}sync();requestAnimationFrame(frame);
