(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.SnowRoll=factory()})(typeof globalThis!=='undefined'?globalThis:this,()=>{
'use strict';const W=800,H=480,FLOOR=420;
const levels=[{name:'한 줄로 굴리기',shelves:[],enemies:[[260,420,250,295,12],[470,420,440,510,18],[670,420,640,725,20]]},{name:'위층에서도',shelves:[{x:260,y:310,w:310}],enemies:[[270,420,230,340,22],[600,420,500,740,28],[430,310,300,535,22]]},{name:'세 갈래 눈길',shelves:[{x:150,y:310,w:230},{x:460,y:310,w:230},{x:315,y:200,w:170}],enemies:[[240,420,210,335,25],[600,420,520,740,32],[260,310,185,345,22],[560,310,490,660,24],[395,200,350,450,18]]}];
function create(stage=0,score=0,lives=3){let l=levels[stage];return{stage,score,lives,status:'ready',time:0,cooldown:0,invincible:1.5,player:{x:100,y:FLOOR,vy:0,grounded:true,face:1},enemies:l.enemies.map((a,id)=>({id,x:a[0],y:a[1],min:a[2],max:a[3],speed:a[4],dir:-1,state:'free',snow:0,thaw:0,vx:0,vy:0,chain:0})),shots:[],defeated:0,bestChain:0,message:'눈을 네 번 맞히고, 가까이에서 밀어 주세요.',event:'ready'};}
function start(s){if(s.status==='ready')s.status='playing'}
function jump(s){let p=s.player;if(s.status!=='playing'||!p.grounded)return false;p.vy=-515;p.grounded=false;return true}
function fire(s){if(s.status!=='playing'||s.cooldown>0)return false;let p=s.player;s.shots.push({x:p.x+p.face*22,y:p.y-20,vx:p.face*380,age:0});s.cooldown=.22;return true}
function push(s){if(s.status!=='playing')return false;let p=s.player,targets=s.enemies.filter(e=>e.state==='frozen'&&Math.abs(e.x-p.x)<=70&&Math.abs(e.y-p.y)<35).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x));if(!targets.length){s.message='눈덩이에 더 가까이 가서 밀어 주세요.';s.event='too-far';return false}let e=targets[0];e.state='rolling';e.vx=p.face*440;e.vy=0;e.chain=0;s.message='굴러갑니다! 같은 길의 적을 만나면 연쇄 점수.';s.event='push';return true}
function defeat(s,e,points){if(e.state==='gone')return;e.state='gone';s.defeated++;s.score+=points}
function step(s,dt,input={}){if(s.status!=='playing')return;dt=Math.min(.025,Math.max(0,dt));s.time+=dt;s.cooldown=Math.max(0,s.cooldown-dt);s.invincible=Math.max(0,s.invincible-dt);let p=s.player,dir=(input.right?1:0)-(input.left?1:0);if(dir)p.face=dir;p.x=Math.max(20,Math.min(W-20,p.x+dir*205*dt));let oldY=p.y;p.vy+=1150*dt;p.y+=p.vy*dt;p.grounded=false;let surfaces=[{x:0,y:FLOOR,w:W},...levels[s.stage].shelves].sort((a,b)=>a.y-b.y);for(let f of surfaces){if(p.vy>=0&&oldY<=f.y+.01&&p.y>=f.y&&p.x+12>f.x&&p.x-12<f.x+f.w){p.y=f.y;p.vy=0;p.grounded=true;break}}
for(let q of s.shots){q.x+=q.vx*dt;q.age+=dt;for(let e of s.enemies){if(e.state==='free'&&Math.abs(q.x-e.x)<23&&Math.abs(q.y-(e.y-20))<22){e.snow++;e.thaw=3;q.age=99;s.event='hit';s.message=`눈 쌓기 ${e.snow}/4`;if(e.snow>=4){e.state='frozen';e.thaw=8;s.event='freeze';s.message='눈덩이가 됐어요. 8초 안에 가까이에서 X로 밀어 주세요.'}break}}}s.shots=s.shots.filter(q=>q.age<.65&&q.x>-20&&q.x<W+20);
for(let e of s.enemies){if(e.state==='free'){e.x+=e.dir*e.speed*dt;if(e.x<e.min){e.x=e.min;e.dir=1}if(e.x>e.max){e.x=e.max;e.dir=-1}if(e.snow>0){e.thaw-=dt;if(e.thaw<=0){e.snow=0;s.event='melt';s.message='덜 쌓인 눈이 녹았어요. 다시 맞혀야 합니다.'}}if(s.invincible<=0&&Math.abs(e.x-p.x)<26&&Math.abs(e.y-p.y)<31){s.lives--;s.invincible=1.8;p.x=100;p.y=FLOOR;p.vy=0;p.grounded=true;s.message='앗! 기회가 줄었어요. 잠시 보호됩니다.';s.event='hurt';if(s.lives<=0){s.status='over';return}}}
else if(e.state==='frozen'){e.thaw-=dt;if(e.thaw<=0){e.state='free';e.snow=0;s.event='escape';s.message='눈덩이가 풀렸어요. 다시 네 번 맞혀 주세요.'}}
else if(e.state==='rolling'){let prev=e.y;e.x+=e.vx*dt;e.vy+=1150*dt;e.y+=e.vy*dt;for(let f of surfaces){if(e.vy>=0&&prev<=f.y+.01&&e.y>=f.y&&e.x+17>f.x&&e.x-17<f.x+f.w){e.y=f.y;e.vy=0;break}}for(let target of s.enemies){if(target!==e&&['free','frozen'].includes(target.state)&&Math.abs(target.x-e.x)<35&&Math.abs(target.y-e.y)<32){e.chain++;defeat(s,target,200*e.chain);s.bestChain=Math.max(s.bestChain,e.chain);s.event='chain';s.message=`${e.chain}연쇄! +${200*e.chain}점`}}if(e.x<-30||e.x>W+30)defeat(s,e,100)}}
if(s.defeated===s.enemies.length){s.status='clear';s.message=s.stage===2?'모든 눈길을 정리했어요!':'이번 눈길 완료! 준비되면 다음 눈길로.';s.event='clear'}}
return{W,H,FLOOR,levels,create,start,jump,fire,push,step};});
