'use strict';
const E=LaneEscape,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');let run=0,state=E.create(),best=0,previous=performance.now();try{best=Number(localStorage.getItem('lane-escape-best'))||0;}catch{}
function round(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function car(x,y,color,player=false){round(x-26,y-40,52,80,10,color);round(x-19,y-24,38,21,5,player?'#263c3c':'#354653');round(x-19,y+19,38,12,4,'#263c3c');for(const dx of [-29,24]){round(x+dx,y-27,5,19,2,'#1a2724');round(x+dx,y+17,5,19,2,'#1a2724');}round(x-20,y-37,10,5,2,'#fff4b9');round(x+10,y-37,10,5,2,'#fff4b9');if(player){ctx.fillStyle='#fff0bc';ctx.fillRect(x-3,y-5,6,18);}}
function paint(){ctx.fillStyle='#315445';ctx.fillRect(0,0,480,640);ctx.fillStyle='#d4c9a4';ctx.fillRect(69,0,11,640);ctx.fillRect(400,0,11,640);ctx.fillStyle='#343e3b';ctx.fillRect(80,0,320,640);ctx.fillStyle='#b7bca6';for(let y=-80+state.road;y<640;y+=80){ctx.fillRect(187,y,5,38);ctx.fillRect(287,y,5,38);ctx.fillStyle='#72967b';ctx.fillRect(28,y,16,30);ctx.fillRect(436,y+24,16,30);ctx.fillStyle='#b7bca6';}for(const v of state.vehicles)car(v.x,v.y,v.color);car(state.x,E.PLAYER_Y,'#f07746',true);ctx.font='12px system-ui';ctx.fillStyle='#e5e5ce';ctx.textAlign='left';ctx.fillText('60 SECOND ROAD',99,29);ctx.textAlign='right';ctx.fillText(Math.round(state.speed)+' px/s',380,29);round(100,44,280,4,2,'#626e62');round(100,44,280*Math.min(state.time/60,1),4,2,'#f4c55d');
if(state.mode!=='playing'){round(96,225,288,144,12,'#f7f3e8f2');ctx.textAlign='center';ctx.fillStyle='#284438';ctx.font='bold 25px system-ui';ctx.fillText({ready:'길 하나 남겨두기',paused:'잠깐 멈춤',over:'다시 출발할까요?',clear:'60초 완주'}[state.mode],240,271);ctx.font='14px system-ui';ctx.fillText(state.mode==='ready'?'← →로 차선을 바꿔 보세요':state.time.toFixed(1)+'초 · '+state.passed+'대 피함',240,303);ctx.fillText(state.mode==='paused'?'P 또는 계속 주행 버튼':state.mode==='playing'?'':'아래 버튼에서 출발',240,334);}
$('time').textContent=state.time.toFixed(1)+'초';$('distance').textContent=Math.floor(state.distance)+'m';$('passed').textContent=state.passed+'대';$('best').textContent=best.toFixed(1)+'초';$('message').textContent=state.message; $('start').textContent=['over','clear'].includes(state.mode)?'다시 출발':state.mode==='ready'?'주행 시작':'처음부터';$('pause').textContent=state.mode==='paused'?'계속 주행':'일시정지';$('pause').disabled=!['playing','paused'].includes(state.mode);$('left').disabled=$('right').disabled=state.mode!=='playing';canvas.setAttribute('aria-label',`자동차 게임, 상태 ${state.mode}, ${state.time.toFixed(1)}초, ${Math.floor(state.distance)}m, 피한 차 ${state.passed}대, 차선 ${state.lane+1}, 속도 ${Math.round(state.speed)}픽셀/초, 차량 `+state.vehicles.map(v=>`${v.lane+1}차선 y${Math.round(v.y)}`).join('; '));}
function pause(){if(state.mode==='playing'){state.mode='paused';state.message='멈춘 동안 차량과 시간도 정지합니다.';}else if(state.mode==='paused'){state.mode='playing';state.message='다시 주행합니다.';}paint();}
$('start').onclick=()=>{state=E.create(731+run++*997);E.start(state);paint();};$('left').onclick=()=>{E.move(state,-1);paint();};$('right').onclick=()=>{E.move(state,1);paint();};$('pause').onclick=pause;
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','a','A','d','D','p','P'].includes(e.key)){e.preventDefault();if(e.repeat)return;if(['p','P'].includes(e.key))pause();else E.move(state,['ArrowLeft','a','A'].includes(e.key)?-1:1);}});window.addEventListener('blur',()=>{if(state.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')pause();});
function tick(now){const dt=Math.min((now-previous)/1000,.05);previous=now;const before=state.mode;E.step(state,dt);if(before==='playing'&&['over','clear'].includes(state.mode)&&state.time>best){best=state.time;try{localStorage.setItem('lane-escape-best',String(best));}catch{}}paint();requestAnimationFrame(tick);}paint();requestAnimationFrame(tick);
