const {test}=require('node:test');const A=require('node:assert/strict');const E=require('./engine');
function ready(pos,value=1){const s=E.createState();s.pieces.CHEONG[0].pos=pos;s.queue=[{value,label:['','도','개','걸','윷','모'][value]}];s.canRoll=false;return s;}
test('29 nodes, four separate reserves per team',()=>{const s=E.createState();A.equal(E.NODE_ORDER.length,29);A.equal(new Set(E.NODE_ORDER).size,29);A.equal(s.pieces.CHEONG.length,4);E.roll(s,1);A.equal(E.move(s,0,0),true);A.deepEqual(s.pieces.CHEONG.map(p=>p.pos),['o1','OUT','OUT','OUT']);A.equal(s.turn,'HONG')});
test('flat face mapping and extra roll',()=>{for(const [flat,value,label] of [[0,5,'모'],[1,1,'도'],[2,2,'개'],[3,3,'걸'],[4,4,'윷']]){const s=E.createState();E.roll(s,flat);A.deepEqual(s.queue,[{value,label}]);A.equal(s.canRoll,value>=4)}});
test('invalid roll no mutation',()=>{for(const input of [-1,5,1.5,undefined,'1']){const s=E.createState(),before=JSON.stringify(s);E.roll(s,input);A.equal(JSON.stringify(s),before)}});
test('finish extra throws before moving and choose queue freely',()=>{const s=E.createState();E.roll(s,4);A.equal(E.move(s,0,0),false);A.deepEqual(E.moves(s,0),[]);E.roll(s,0);E.roll(s,1);A.equal(s.queue.length,3);A.equal(E.move(s,2,0),true);A.equal(s.pieces.CHEONG[0].pos,'o1');A.equal(s.turn,'CHEONG');A.equal(s.queue.length,2)});
test('corner shortcuts only when starting there',()=>{A.equal(E.computePath('o4',2).at(-1),'o6');A.equal(E.computePath('o5',3).at(-1),'C');A.equal(E.computePath('o5',4).at(-1),'a4');A.equal(E.computePath('o10',5).at(-1),'b5');A.equal(E.computePath('C',3).at(-1),'o20');A.equal(E.computePath('C',4).at(-1),'FINISH');A.equal(E.computePath('a2',2).at(-1),'a4');A.equal(E.computePath('b2',2).at(-1),'b4')});
test('own pieces stack on landing then move together',()=>{const s=ready('o1');s.pieces.CHEONG[1].pos='o2';E.move(s,0,0);A.deepEqual(s.pieces.CHEONG.slice(0,2).map(p=>p.pos),['o2','o2']);s.turn='CHEONG';s.queue=[{value:2,label:'개'}];s.canRoll=false;E.move(s,0,1);A.deepEqual(s.pieces.CHEONG.slice(0,2).map(p=>p.pos),['o4','o4'])});
test('catch whole opposing stack grants exactly one throw even with empty queue',()=>{const s=ready('o1');s.pieces.HONG[0].pos='o2';s.pieces.HONG[1].pos='o2';E.move(s,0,0);A.deepEqual(s.pieces.HONG.map(p=>p.pos),['OUT','OUT','OUT','OUT']);A.equal(s.turn,'CHEONG');A.equal(s.canRoll,true);E.roll(s,2);A.equal(s.canRoll,false);E.move(s,0,0);A.equal(s.turn,'HONG')});
test('yut capture does not create duplicate bonus',()=>{const s=ready('o1',4);s.pieces.HONG[0].pos='o5';E.move(s,0,0);A.equal(s.turn,'HONG');A.equal(s.canRoll,true)});
test('exit exact landing not yet finish, overshoot finishes',()=>{let s=ready('o19');E.move(s,0,0);A.equal(s.pieces.CHEONG[0].pos,'o20');s=ready('o19',3);E.move(s,0,0);A.equal(s.pieces.CHEONG[0].pos,'FINISH')});
test('stack of four finishes and no input after victory',()=>{const s=ready('o20');s.pieces.CHEONG.forEach(p=>p.pos='o20');E.move(s,0,0);A.equal(s.winner,'CHEONG');const before=JSON.stringify(s);A.equal(E.move(s,0,0),false);E.roll(s,4);A.equal(JSON.stringify(s),before)});
test('undo restores throw/capture/finish completely',()=>{for(const s of [E.createState(),ready('o1'),ready('o20')]){s.pieces.HONG[0].pos='o2';const before=JSON.stringify(s);if(s.canRoll)E.roll(s,3);else E.move(s,0,0);A.equal(E.undo(s),true);A.equal(JSON.stringify(s),before)}});
test('invalid move indices leave state intact',()=>{const s=ready('o1');for(const [r,p] of [[-1,0],[1,0],[.5,0],[0,4],[0,-1],[NaN,0],[0,undefined]]){const before=JSON.stringify(s);A.equal(E.move(s,r,p),false);A.equal(JSON.stringify(s),before)}});
