'use strict';
const {Game,chart,BEAT}=BeatWindow,g=new Game(),$=id=>document.getElementById(id),c=document.querySelector('canvas'),ctx=c.getContext('2d');
let audio=null,origin=0,frozen=0,nextBeat=0,runOffset=0,flash=[0,0],pressed=new Set();
function tone(at,index){if(!$('sound').checked)return;const o=audio.createOscillator(),v=audio.createGain();o.type=index%4===0?'sine':'triangle';o.frequency.setValueAtTime(index%4===0?170:660,at);v.gain.setValueAtTime(.0001,at);v.gain.exponentialRampToValueAtTime(.075,at+.005);v.gain.exponentialRampToValueAtTime(.0001,at+.07);o.connect(v);v.connect(audio.destination);o.start(at);o.stop(at+.08)}
async function start(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();if(audio.state!=='running')throw Error('audio paused');g.start();runOffset=Number($('offset').value)/1000;origin=audio.currentTime+.1;nextBeat=0;frozen=0;$('offset').disabled=true;$('start').disabled=true;$('pause').disabled=false;$('pause').textContent='일시정지';$('result').textContent='';}catch(e){$('feedback').textContent='소리를 시작하지 못했어요. 시작 버튼을 다시 눌러 주세요.'}}
function time(){return Math.max(0,audio.currentTime-origin)}
function hit(lane){if(g.phase!=='playing')return;g.hit(lane,time()-runOffset);flash[lane]=performance.now()+140;update()}
async function pause(){if(g.phase==='playing'){frozen=time();g.phase='paused';await audio.suspend();$('pause').textContent='계속';$('feedback').textContent='잠시 쉬는 중';}else if(g.phase==='paused'){await audio.resume();origin=audio.currentTime-frozen;g.phase='playing';$('pause').textContent='일시정지'}}
function reset(){g.reset();if(audio)audio.suspend();pressed.clear();$('start').disabled=false;$('pause').disabled=true;$('pause').textContent='일시정지';$('offset').disabled=false;$('result').textContent='';update();$('feedback').textContent='시작을 누르면 2초 뒤 첫 노트!'}
function update(){for(const n of ['score','combo','hits','misses'])$(n).textContent=g[n];if(g.phase==='playing')$('feedback').textContent=g.last;if(g.phase==='finished'){$('start').disabled=false;$('pause').disabled=true;$('offset').disabled=false;$('feedback').textContent=g.last;const mean=g.errors.length?Math.round(g.errors.reduce((a,b)=>a+b,0)/g.errors.length*1000):null;$('result').textContent=`맞힘 ${g.hits}/32 · 최고 연속 ${g.best}`+(mean===null?'':` · 평균 오차 ${mean}ms`);}}
function draw(){ctx.clearRect(0,0,430,440);ctx.fillStyle='#14232f';ctx.fillRect(0,0,430,440);for(let lane=0;lane<2;lane++){ctx.fillStyle=performance.now()<flash[lane]?(lane?'#70506b':'#3b725a'):'#1d303e';ctx.fillRect(30+lane*195,12,175,415)}ctx.strokeStyle='#496171';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(215,0);ctx.lineTo(215,440);ctx.stroke();for(const n of g.notes){if(n.status!=='pending')continue;const y=360-(n.time-(g.phase==='playing'?time():g.phase==='paused'?frozen:g.time))*170;if(y<-20||y>430)continue;ctx.fillStyle=n.lane?'#edacd7':'#ade7b7';ctx.beginPath();ctx.roundRect(55+n.lane*195,y-9,125,18,8);ctx.fill();}ctx.shadowBlur=13;ctx.shadowColor='#ecf9c9';ctx.strokeStyle='#ecf9c9';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(25,360);ctx.lineTo(405,360);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#c3d3d9';ctx.font='600 14px system-ui';ctx.textAlign='center';ctx.fillText('D',115,400);ctx.fillText('K',310,400);if(g.phase==='ready'||g.phase==='paused'){ctx.fillStyle='#10202cd9';ctx.fillRect(40,140,350,115);ctx.fillStyle='#edf6e8';ctx.font='600 23px system-ui';ctx.fillText(g.phase==='paused'?'잠시 쉬는 중':'박자 사이',215,180);ctx.font='15px system-ui';ctx.fillText(g.phase==='paused'?'계속 버튼으로 이어가요':'밝은 선에서 D / K',215,220)}if(g.phase==='finished'){ctx.fillStyle='#132d26ec';ctx.fillRect(40,140,350,110);ctx.fillStyle='#e8f8d9';ctx.font='600 24px system-ui';ctx.fillText('한 곡 끝!',215,186);ctx.font='16px system-ui';ctx.fillText(`${g.score}점 · ${g.hits}개 맞힘`,215,224)}}
function frame(){if(g.phase==='playing'){const t=time();g.advance(Math.max(0,t-runOffset));while(nextBeat*BEAT+2<=t+.08&&nextBeat<32){const at=origin+2+nextBeat*BEAT;if(at>audio.currentTime+.002)tone(at,nextBeat);nextBeat++;}update()}draw();requestAnimationFrame(frame)}
$('start').onclick=start;$('pause').onclick=pause;$('reset').onclick=reset;$('offset').oninput=()=>$('offsetLabel').textContent=$('offset').value+'ms';
for(const [id,lane]of [['left',0],['right',1]]){$(id).onpointerdown=e=>{e.preventDefault();hit(lane)};$(id).onclick=e=>{if(e.detail===0)hit(lane)}}
document.addEventListener('keydown',e=>{const lane={KeyD:0,KeyK:1}[e.code];if(lane===undefined||e.target.matches('input'))return;e.preventDefault();if(e.repeat||pressed.has(e.code))return;pressed.add(e.code);hit(lane)});document.addEventListener('keyup',e=>pressed.delete(e.code));window.addEventListener('blur',()=>{pressed.clear();if(g.phase==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.phase==='playing')pause()});frame();
