'use strict';const E=SplitPop,$=id=>document.getElementById(id),c=$('game'),g=c.getContext('2d');let s=E.create(),held={},last=0,acc=0,notice='';
function sync(){ $('round').textContent=`${s.stage+1} / 3`;$('score').textContent=s.score;$('balls').textContent=s.balls.length;$('lives').textContent=s.lives;$('start').hidden=!['ready','clear'].includes(s.status)||s.status==='clear'&&s.stage===2;$('start').textContent=s.status==='clear'?'다음 라운드 →':'시작';$('pause').disabled=!['playing','paused'].includes(s.status);$('pause').textContent=s.status==='paused'?'계속':'일시정지';let msg={ready:'서두르지 말고 공이 지나갈 길을 보세요. 시작을 누르면 움직입니다.',playing:'공을 나누면 개수가 늘어납니다. 낮게 튀는 작은 공을 조심하세요.',paused:'잠깐 멈췄습니다. 계속을 누르면 이어집니다.',clear:s.stage===2?'세 라운드 완료! 모든 공을 정리했습니다.':'이번 라운드 완료! 준비되면 다음 라운드로 넘어가세요.',over:'기회를 모두 썼습니다. 처음부터 다시 도전해 보세요.'}[s.status];if(msg!==notice){notice=msg;$('status').textContent=msg;}c.setAttribute('aria-label',`라운드 ${s.stage+1}, 점수 ${s.score}, 남은 공 ${s.balls.length}, 기회 ${s.lives}. ${msg}`);}
function draw(){g.clearRect(0,0,800,440);let bg=g.createLinearGradient(0,0,0,440);bg.addColorStop(0,'#25334f');bg.addColorStop(1,'#162039');g.fillStyle=bg;g.fillRect(0,0,800,440);g.strokeStyle='#ffffff08';for(let x=0;x<800;x+=40){g.beginPath();g.moveTo(x,0);g.lineTo(x,E.FLOOR);g.stroke()}for(let y=32;y<E.FLOOR;y+=40){g.beginPath();g.moveTo(0,y);g.lineTo(800,y);g.stroke()}g.fillStyle='#394960';g.fillRect(0,E.FLOOR,800,48);g.fillStyle='#d0ae77';g.fillRect(0,E.FLOOR,800,3);
for(let q of s.shots){g.strokeStyle='#ffe5a3';g.lineWidth=4;g.beginPath();g.moveTo(q.x,q.bottom);g.lineTo(q.x,q.top);g.stroke();g.fillStyle='#fff2cc';g.beginPath();g.moveTo(q.x,q.top-7);g.lineTo(q.x-7,q.top+7);g.lineTo(q.x+7,q.top+7);g.fill()}
for(let b of s.balls){g.fillStyle=['#8cd8bd','#ba9de8','#ed957d'][b.size];g.shadowColor=g.fillStyle;g.shadowBlur=9;g.beginPath();g.arc(b.x,b.y,b.r,0,Math.PI*2);g.fill();g.shadowBlur=0;g.strokeStyle='#ffffff80';g.lineWidth=2;g.stroke();g.fillStyle='#ffffff66';g.beginPath();g.ellipse(b.x-b.r*.3,b.y-b.r*.32,b.r*.25,b.r*.15,-.5,0,Math.PI*2);g.fill();}
let p=s.player;g.globalAlpha=s.invincible>0&&Math.floor(s.time*8)%2===0?.55:1;g.fillStyle='#e4c79e';g.beginPath();g.roundRect(p.x-13,E.FLOOR-27,26,25,5);g.fill();g.fillStyle='#eee4cb';g.beginPath();g.arc(p.x,E.FLOOR-32,12,0,Math.PI*2);g.fill();g.fillStyle='#ef927d';g.fillRect(p.x-14,E.FLOOR-42,28,7);g.fillStyle='#17283e';g.fillRect(p.x-6,E.FLOOR-33,3,3);g.fillRect(p.x+3,E.FLOOR-33,3,3);g.globalAlpha=1;
if(s.status!=='playing'){g.fillStyle='#1118279e';g.fillRect(0,0,800,440);g.textAlign='center';g.fillStyle='#fff0d9';g.font='bold 32px system-ui';g.fillText({ready:'한 번 맞히면, 둘로!',paused:'잠깐 쉬어가기',clear:s.stage===2?'모두 나눴어요!':'라운드 클리어',over:'다시 한 판?'}[s.status],400,193);g.font='16px system-ui';g.fillStyle='#c8d1e4';g.fillText(s.status==='paused'?`남은 공 ${s.balls.length}개 · 점수 ${s.score}`:'좌우로 피하고, 위로 쏘세요.',400,230);}}
function frame(t){let dt=last?Math.min((t-last)/1000,.1):0;last=t;if(s.status==='playing'){acc+=dt;while(acc>=1/120){E.step(s,1/120,held);acc-=1/120;}}else acc=0;sync();draw();requestAnimationFrame(frame)}
function pause(){if(s.status==='playing'){s.status='paused';held={}}else if(s.status==='paused')s.status='playing';sync();draw()}
$('start').onclick=()=>{if(s.status==='clear')s=E.create(s.stage+1,s.score,s.lives);E.start(s);held={};sync()};$('pause').onclick=pause;$('restart').onclick=()=>{s=E.create();held={};sync();draw()};
for(let[id,k]of[['left','left'],['right','right'],['shoot','fire']]){let b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held[k]=true;if(k==='fire')E.fire(s)};for(let ev of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>held[k]=false);b.onclick=e=>{if(e.detail===0&&k==='fire')E.fire(s)};}
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const map={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',' ':'fire'};if(map[e.key]){e.preventDefault();held[map[e.key]]=true;if(e.key===' ')E.fire(s)}if(e.key.toLowerCase()==='p'&&!e.repeat){e.preventDefault();pause()}});document.addEventListener('keyup',e=>{const map={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',' ':'fire'};if(map[e.key])held[map[e.key]]=false});window.addEventListener('blur',()=>{held={};if(s.status==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){held={};if(s.status==='playing')pause()}});sync();requestAnimationFrame(frame);
