const test = require('node:test');
const assert = require('node:assert/strict');
const E = require('./engine.js');
function rng(seed){return ()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
function game(seed=42){return E.createGame({rng:rng(seed)});}
test('81 cells, 10 mines configured, no mines placed before reveal',()=>{const s=game();assert.equal(s.cells.length,81);assert.equal(s.mineCount,10);assert.equal(s.minesPlaced,false);assert.equal(s.status,'ready');});
test('first reveal is safe across every beginner cell and 30 seeds',()=>{for(let seed=1;seed<=30;seed++)for(let i=0;i<81;i++){const s=game(seed);E.revealCell(s,i%9,Math.floor(i/9));assert.notEqual(s.status,'lost');assert.equal(s.cells[i].mine,false);assert.equal(s.cells.filter(c=>c.mine).length,10);}});
test('numbers equal actual adjacent mines without wrapping edges',()=>{const s=game();E.revealCell(s,4,4);for(let i=0;i<81;i++){if(s.cells[i].mine)continue;let count=0;const x=i%9,y=Math.floor(i/9);for(let yy=Math.max(0,y-1);yy<=Math.min(8,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(8,x+1);xx++)count+=Number(s.cells[yy*9+xx].mine);assert.equal(s.cells[i].adjacent,count);}});
test('flag blocks reveal and does not start game',()=>{const s=game();E.toggleFlag(s,0,0);E.revealCell(s,0,0);assert.equal(s.status,'ready');assert.equal(s.revealedCount,0);assert.equal(E.getRemainingMines(s),9);E.toggleFlag(s,0,0);assert.equal(E.getRemainingMines(s),10);});
test('zero mine board opens fully and wins',()=>{const s=E.createGame({width:9,height:9,mines:0,rng:rng(1)});E.revealCell(s,0,0);assert.equal(s.revealedCount,81);assert.equal(s.status,'won');});
test('flood preserves a flagged safe cell, unflag and reveal finishes',()=>{const s=E.createGame({width:4,height:4,mines:0,rng:rng(1)});E.toggleFlag(s,3,3);E.revealCell(s,0,0);assert.equal(s.revealedCount,15);assert.equal(s.status,'playing');E.toggleFlag(s,3,3);E.revealCell(s,3,3);assert.equal(s.status,'won');});
test('hitting a mine loses and reveals all mines',()=>{const s=game();E.revealCell(s,4,4);const i=s.cells.findIndex(c=>c.mine);E.revealCell(s,i%9,Math.floor(i/9));assert.equal(s.status,'lost');assert.equal(s.explodedIndex,i);assert.ok(s.cells.filter(c=>c.mine).every(c=>c.revealed));});
test('revealing all safe cells wins without requiring flags',()=>{const s=game();E.revealCell(s,4,4);s.cells.forEach((c,i)=>{if(!c.mine)E.revealCell(s,i%9,Math.floor(i/9));});assert.equal(s.status,'won');assert.equal(s.revealedCount,71);});
test('finished game ignores further input',()=>{const s=game();E.revealCell(s,4,4);const i=s.cells.findIndex(c=>c.mine);E.revealCell(s,i%9,Math.floor(i/9));const before=JSON.stringify(s);E.toggleFlag(s,0,0);E.revealCell(s,0,0);assert.equal(JSON.stringify(s),before);});
test('reset clears revealed cells flags and status',()=>{let s=game();E.toggleFlag(s,0,0);E.revealCell(s,4,4);s=E.resetGame(s);assert.equal(s.status,'ready');assert.equal(s.flagCount,0);assert.equal(s.revealedCount,0);assert.equal(s.minesPlaced,false);});
test('first reveal opens a zero cell with safe neighbors at all 81 starts',()=>{for(let seed=1;seed<=20;seed++)for(let i=0;i<81;i++){const s=game(seed);const x=i%9,y=Math.floor(i/9);E.revealCell(s,x,y);assert.equal(s.cells[i].adjacent,0);for(let yy=Math.max(0,y-1);yy<=Math.min(8,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(8,x+1);xx++)assert.equal(s.cells[yy*9+xx].mine,false);assert.equal(s.cells.filter(c=>c.mine).length,10);}});
test('dense custom board falls back to first cell protection preserving mine count',()=>{const s=E.createGame({width:3,height:3,mines:8,rng:rng(3)});E.revealCell(s,1,1);assert.equal(s.cells[4].mine,false);assert.equal(s.cells.filter(c=>c.mine).length,8);assert.equal(s.status,'won');});
