'use strict';
const game=new CloudTrail.Game('tuned'),$=id=>document.getElementById(id),c=$('board').getContext('2d');const held={left:false,right:false},until={left:0,right:0};let clock=0,last=0,acc=0;
function clear(){held.left=held.right=false;until.left=until.right=0;}
function sync(){$('coins').textContent=game.coins.filter(x=>x.taken).length+' / 3';$('deaths').textContent=game.deaths;$('checkpoint').textContent=game.checkpoint?'중간 깃발':'출발점';$('status').textContent=game.paused?'잠깐 쉬는 중. 이어하기로 계속하세요.':game.message;$('pause').textContent=game.paused?'이어하기':'일시정지';$('pause').disabled=game.phase==='won';for(const id of ['left','right','jump'])$(id).disabled=game.paused||game.phase==='won';$('physics').textContent=game.profile==='prototype'?'초기 점프 · 속도 520 / 중력 1800':'점프 여유 · 발판 끝 90ms / 착지 입력 120ms';}
function pause(){if(game.phase!=='playing')return;game.paused=!game.paused;clear();sync();}$('pause').onclick=pause;$('reset').onclick=()=>{game.reset();clear();sync();};$('jump').onclick=()=>{game.requestJump();sync();};
for(const id of ['left','right']){const b=$(id);let began=0;b.onpointerdown=e=>{began=performance.now();held[id]=true;b.setPointerCapture(e.pointerId);};b.onpointerup=()=>{held[id]=false;if(performance.now()-began<150)until[id]=clock+.25;};b.onpointercancel=()=>{held[id]=false;until[id]=0;};b.onclick=e=>{if(e.detail===0)until[id]=clock+.25;};}
addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if(['ArrowLeft','ArrowRight','ArrowUp','Space'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft')held.left=true;if(e.code==='ArrowRight')held.right=true;if(e.repeat)return;if(e.code==='ArrowUp'||e.code==='Space')game.requestJump();if(e.code==='KeyP')pause();});addEventListener('keyup',e=>{if(e.code==='ArrowLeft')held.left=false;if(e.code==='ArrowRight')held.right=false;});function blur(){clear();if(game.phase==='playing'){game.paused=true;sync();}}addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});
function round(x,y,w,h,r,color){c.fillStyle=color;c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}function circle(x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}function cloud(x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);circle(0,0,24,'#f8faf0');circle(29,-8,32,'#f8faf0');circle(62,3,21,'#f8faf0');round(-24,0,107,22,11,'#f8faf0');c.restore();}
function flag(x,y,active){c.strokeStyle='#476965';c.lineWidth=4;c.beginPath();c.moveTo(x,y);c.lineTo(x,y-70);c.stroke();c.fillStyle=active?'#dc9b61':'#f3dfbb';c.beginPath();c.moveTo(x,y-70);c.lineTo(x+37,y-57);c.lineTo(x,y-43);c.fill();}
function draw(t){c.fillStyle='#b6d8c8';c.fillRect(0,0,960,480);const cam=game.camera;circle(830-cam*.1,75,36,'#f8e5b0');cloud(120-cam*.18,80,.8);cloud(420-cam*.15,135,.55);cloud(710-cam*.12,65,.65);c.fillStyle='#91bea9';c.beginPath();c.moveTo(0,320);for(let i=0;i<7;i++)c.quadraticCurveTo(i*180+80-cam*.08,215,(i+1)*180-cam*.08,330);c.lineTo(960,480);c.lineTo(0,480);c.fill();c.save();c.translate(-cam,0);
for(const s of CloudTrail.solids){round(s.x,s.y,s.w,s.h,5,'#739c82');round(s.x,s.y,s.w,7,3,'#3f7563');for(let x=s.x+20;x<s.x+s.w;x+=40){c.strokeStyle='#a4b898';c.lineWidth=2;c.beginPath();c.moveTo(x,s.y+18);c.lineTo(x+8,s.y+18);c.stroke();}}c.fillStyle='#eef3de';c.font='13px system-ui';c.fillText('첫 발판',282,355);c.fillStyle='#395f56';c.fillText('틈을 넘어요',630,460);flag(735,420,game.checkpoint);flag(1540,420,true);
for(const coin of game.coins){if(coin.taken)continue;c.save();c.translate(coin.x,coin.y+Math.sin(t/300)*3);c.fillStyle='#ffe4a0';c.beginPath();for(let i=0;i<10;i++){let r=i%2?6:13,a=-Math.PI/2+i*Math.PI/5;c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();c.restore();}
let p=game.player;round(p.x-14,p.y-21,28,38,10,'#ec956d');round(p.x-16,p.y-20,32,8,5,'#fbf0d6');circle(p.x+p.face*7,p.y-6,2.7,'#38584e');round(p.x-13,p.y+15,10,7,3,'#3f7060');round(p.x+3,p.y+15,10,7,3,'#3f7060');c.restore();if(game.paused||game.phase==='won'){round(230,155,500,145,18,'#f4f1e8ed');c.textAlign='center';c.fillStyle='#315951';c.font='bold 29px system-ui';c.fillText(game.paused?'구름을 잠깐 바라보기':'깃발에 도착했어요!',480,205);c.font='15px system-ui';c.fillText(game.paused?'이어하기 버튼으로 계속':`별 ${game.coins.filter(x=>x.taken).length}개 · 다시 출발 ${game.deaths}번`,480,244);c.textAlign='left';}}
function frame(t){if(!last)last=t;acc+=Math.min(t-last,50)/1000;last=t;while(acc>=CloudTrail.DT){clock+=CloudTrail.DT;game.step({left:held.left||clock<until.left,right:held.right||clock<until.right});acc-=CloudTrail.DT;}sync();draw(t);requestAnimationFrame(frame);}sync();requestAnimationFrame(frame);
