'use strict';
const {$}= { $:id=>document.getElementById(id)};
const canvas=$('board'),ctx=canvas.getContext('2d');let game=new Sling.Game(),angle=25,power=75,dragging=false,pull=null,acc=0,last=0,trail=[],lastUi='',guideKey='',guidePoints=[];
function sync(){const state=[game.level,game.shots,game.hits,game.phase,game.paused,game.message].join('|');if(state===lastUi)return;lastUi=state;$('level').textContent=`${game.level+1} / 3 · ${Sling.stages[game.level].name}`;$('shots').textContent='●'.repeat(game.shots)||'0';$('hits').textContent=`${game.hits} / ${game.targets.length}`;$('message').textContent=game.paused?'잠깐 쉬는 중 — 이어하기를 누르세요.':game.message;$('pause').textContent=game.paused?'이어하기':'일시정지';$('launch').disabled=game.phase!=='ready'||game.paused;$('angle').disabled=$('power').disabled=game.phase!=='ready'||game.paused;$('next').hidden=game.phase!=='won';$('next').textContent=game.level===2?'처음부터 다시':'다음 판 →';}
function launch(){if(game.launch(angle,power))trail=[];sync();}
function reset(level=game.level){game.load(level);dragging=false;pull=null;trail=[];acc=0;sync();}
function setAim(a,p){angle=Math.round(Math.max(5,Math.min(75,a)));power=Math.round(Math.max(20,Math.min(100,p)));$('angle').value=angle;$('power').value=power;$('angleValue').value=angle+'°';$('powerValue').value=power+'%';}
$('angle').oninput=()=>setAim(+$('angle').value,power);$('power').oninput=()=>setAim(angle,+$('power').value);$('launch').onclick=launch;$('retry').onclick=()=>reset();$('next').onclick=()=>reset((game.level+1)%3);$('pause').onclick=()=>{game.paused=!game.paused;dragging=false;pull=null;sync();};
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1000/r.width,y:(e.clientY-r.top)*560/r.height};}
function aim(e){const p=pos(e),dx=Math.max(1,Sling.ANCHOR.x-p.x),dy=Math.max(0,p.y-Sling.ANCHOR.y);setAim(Math.atan2(dy,dx)*180/Math.PI,Math.min(100,Math.hypot(dx,dy)/110*100));pull={x:Sling.ANCHOR.x-Math.cos(angle*Math.PI/180)*power*1.1,y:Sling.ANCHOR.y+Math.sin(angle*Math.PI/180)*power*1.1};}
canvas.onpointerdown=e=>{if(game.phase!=='ready'||game.paused)return;const p=pos(e);if(Math.hypot(p.x-180,p.y-370)>60)return;dragging=true;canvas.setPointerCapture(e.pointerId);aim(e);};canvas.onpointermove=e=>{if(dragging)aim(e);};canvas.onpointerup=e=>{if(!dragging)return;aim(e);dragging=false;pull=null;launch();};canvas.onpointercancel=()=>{dragging=false;pull=null;};
addEventListener('keydown',e=>{if(e.target.matches('input,button')||e.repeat)return;if(e.code==='Space'){e.preventDefault();launch();}if(e.code==='KeyR')reset();if(e.code==='KeyP'){$('pause').click();}});
function blur(){if(game.phase==='flying'){game.paused=true;sync();}dragging=false;pull=null;}
addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function line(x1,y1,x2,y2,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function draw(){ctx.clearRect(0,0,1000,560);ctx.fillStyle='#e8efdf';ctx.fillRect(0,0,1000,560);circle(825,98,56,'#f9d486');ctx.fillStyle='#d6e2cf';ctx.beginPath();ctx.moveTo(0,380);ctx.bezierCurveTo(180,150,310,380,450,280);ctx.bezierCurveTo(700,130,780,310,1000,210);ctx.lineTo(1000,480);ctx.lineTo(0,480);ctx.fill();ctx.fillStyle='#c4d7bd';ctx.beginPath();ctx.moveTo(0,430);ctx.bezierCurveTo(300,260,470,420,630,350);ctx.bezierCurveTo(800,290,920,450,1000,380);ctx.lineTo(1000,480);ctx.lineTo(0,480);ctx.fill();ctx.fillStyle='#335c4d';ctx.fillRect(0,480,1000,80);ctx.fillStyle='#83a279';ctx.fillRect(0,480,1000,6);ctx.font='12px system-ui';ctx.fillStyle='#c1d3bd';ctx.fillText('작은 변화로, 다른 궤도.',35,525);ctx.textAlign='right';ctx.fillText('POCKET SLING / 0'+(game.level+1),965,525);ctx.textAlign='left';
 for(let x=300;x<1000;x+=100){line(x,481,x,490,'#83a279',1);}
 if(game.phase==='ready'&&$('guide').checked){const key=angle+':'+power+':'+game.level+':'+game.shots;if(key!==guideKey){guidePoints=Sling.predict(angle,power,[...game.boxes,...game.targets.filter(t=>t.alive)]);guideKey=key;}guidePoints.forEach((p,i)=>{circle(p.x,p.y,3.4-i*.05,'#6e927d');});}
 trail.forEach((p,i)=>circle(p.x,p.y,2,'rgba(237,112,67,'+(i/trail.length*.35)+')'));
 line(180,477,180,408,'#825d3e',15);line(180,415,155,357,'#956947',12);line(180,415,204,357,'#956947',12);
 for(const b of game.boxes){ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);const{w,h}=b.size;ctx.fillStyle='#c58e58';ctx.strokeStyle='#976b43';ctx.lineWidth=2;ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeRect(-w/2+3,-h/2+3,w-6,h-6);line(-w/2+6,-h/2+7,w/2-6,h/2-7,'#e0b780',3);line(w/2-6,-h/2+7,-w/2+6,h/2-7,'#e0b780',3);ctx.restore();}
 for(const b of game.targets){if(!b.alive)continue;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);circle(0,0,20,'#3b9982');circle(-6,-3,3,'#163f35');circle(6,-3,3,'#163f35');line(-5,7,5,7,'#cff1dd',2);ctx.restore();}
 for(const b of game.balls){circle(b.position.x,b.position.y,17,'#ed7043');circle(b.position.x-5,b.position.y-6,5,'#ffae72');}
 if(game.phase==='ready'){const p=pull||Sling.ANCHOR;line(155,357,p.x,p.y,'#704a33',5);circle(p.x,p.y,17,'#ed7043');circle(p.x-5,p.y-6,5,'#ffae72');line(204,357,p.x,p.y,'#845735',5);ctx.font='600 13px system-ui';ctx.fillStyle='#385e4d';ctx.fillText(dragging?'손을 놓으면 발사':'← 당겨서 발사',80,320);}
 if(game.paused||game.phase==='won'||game.phase==='lost'){ctx.fillStyle='rgba(247,243,233,.88)';ctx.fillRect(290,173,420,136);ctx.textAlign='center';ctx.fillStyle='#193c39';ctx.font='bold 30px system-ui';ctx.fillText(game.paused?'잠깐 쉬어가기':game.phase==='won'?'잘 맞혔어요!':'한 번 더 당겨볼까요?',500,226);ctx.font='15px system-ui';ctx.fillText(game.paused?'이어하기 버튼으로 계속':game.phase==='won'?'다음 판 버튼을 눌러 주세요':'이 판 다시 · 각도와 힘을 바꿔 보세요',500,266);ctx.textAlign='left';}}
function frame(t){if(!last)last=t;acc+=Math.min(t-last,50);last=t;while(acc>=Sling.DT){game.step();acc-=Sling.DT;}if(game.phase==='flying'&&!game.paused){trail.push({...game.active.position});if(trail.length>90)trail.shift();}sync();draw();requestAnimationFrame(frame);}sync();requestAnimationFrame(frame);
