'use strict';const E=FruitLoft,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');let state=E.create(),keys={},walk=0,last=0,acc=0,lastStatus='';
function sync(){let s=state;$('stage').textContent=`${s.stage+1} / 3`;$('fruit').textContent=`${s.collected} / 12`;$('score').textContent=s.score;$('lives').textContent=s.lives;$('start').hidden=!['ready','clear'].includes(s.status)||s.status==='clear'&&s.stage===2;$('start').textContent=s.status==='clear'?'다음 창고 →':'시작';$('pause').disabled=!['playing','paused'].includes(s.status);$('pause').textContent=s.status==='paused'?'계속':'일시정지';$('left').setAttribute('aria-pressed',walk===-1);$('right').setAttribute('aria-pressed',walk===1);let msg=s.status==='paused'?'잠깐 쉬는 중입니다. 계속을 누르면 이어집니다.':s.status==='over'?'기회를 모두 썼어요. 처음부터 다시 시작할 수 있습니다.':s.notice;if(msg!==lastStatus){$('status').textContent=msg;lastStatus=msg}canvas.setAttribute('aria-label',`창고 ${s.stage+1}, 과일 ${s.collected}/12, 점수 ${s.score}, 기회 ${s.lives}, 위치 ${Math.round(s.player.x)}, ${s.player.floor===null?'이동 중':s.player.floor+1+'층'}. ${msg}`)}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function raccoon(p){ctx.save();ctx.translate(p.x,p.y);ctx.scale(p.face,1);ctx.rotate(-.04);ellipse(-17,-12,16,8,'#8b9693');ctx.fillStyle='#405150';for(let i=0;i<3;i++)ctx.fillRect(-31+i*7,-18,3,12);ellipse(0,-15,12,15,'#b9c2ba');ellipse(-7,-36,6,7,'#b8bcb0');ellipse(8,-36,6,7,'#b8bcb0');ellipse(0,-28,14,12,'#d2d1ba');ellipse(-6,-29,6,5,'#314447');ellipse(6,-29,6,5,'#314447');ellipse(-5,-30,1.7,2,'#fff9df');ellipse(7,-30,1.7,2,'#fff9df');ellipse(1,-23,3,2,'#263b3f');ctx.fillStyle='#dc8154';ctx.fillRect(-10,-18,21,5);ctx.fillRect(8,-16,5,10);ctx.restore()}
function draw(){let s=state,g=ctx;g.fillStyle='#173132';g.fillRect(0,0,800,540);g.fillStyle='#203c3c';for(let x=0;x<800;x+=80)g.fillRect(x,0,3,540);for(let y of E.FLOORS){g.fillStyle='#876348';g.fillRect(25,y,750,14);g.fillStyle='#d6ad74';g.fillRect(25,y,750,4);g.fillStyle='#102829';g.fillRect(25,y+14,750,5)}for(let l of E.LADDERS){g.strokeStyle='#b09873';g.lineWidth=5;for(let x of[l.x-11,l.x+11]){g.beginPath();g.moveTo(x,E.FLOORS[l.to]);g.lineTo(x,E.FLOORS[l.from]);g.stroke()}for(let y=E.FLOORS[l.to]+10;y<E.FLOORS[l.from];y+=17){g.beginPath();g.moveTo(l.x-11,y);g.lineTo(l.x+11,y);g.stroke()}}
for(let f of s.fruits){if(f.taken)continue;let y=f.y+Math.sin(s.time*3+f.x)*2;if(f.kind===0){ellipse(f.x-4,y,8,10,'#ef9277');ellipse(f.x+4,y,8,10,'#ed7c61')}if(f.kind===1){ellipse(f.x,y+3,10,10,'#f1c46c');ellipse(f.x,y-4,6,8,'#f1c46c')}if(f.kind===2){for(let[a,b]of[[-6,-4],[5,-4],[-7,5],[5,5],[0,11]])ellipse(f.x+a,y+b,5,5,'#b3a4df')}g.fillStyle='#75ab82';g.beginPath();g.ellipse(f.x+4,y-12,6,3,-.6,0,7);g.fill()}
for(let e of s.enemies){g.fillStyle='#ba966f';g.beginPath();g.moveTo(e.x-17,e.y-4);for(let i=0;i<6;i++){g.lineTo(e.x-17+i*6,e.y-23);g.lineTo(e.x-14+i*6,e.y-14)}g.lineTo(e.x+20,e.y-4);g.closePath();g.fill();ellipse(e.x,e.y-8,18,8,'#96785f');ellipse(e.x+Math.sign(e.v)*12,e.y-10,2,2,'#fff3d7')}
g.globalAlpha=s.invincible>0&&Math.floor(s.time*8)%2===0?.45:1;raccoon(s.player);g.globalAlpha=1;g.font='12px system-ui';g.textAlign='left';g.fillStyle='#82a09b';for(let i=0;i<4;i++)g.fillText(`${i+1}F`,7,E.FLOORS[i]-40);
if(s.status!=='playing'){g.fillStyle='#0d2225b8';g.fillRect(0,0,800,540);g.textAlign='center';g.fillStyle='#fff1d3';g.font='bold 32px system-ui';g.fillText({ready:'오늘은 과일을 모으는 날',paused:'잠깐 쉬어가기',clear:s.stage===2?'창고 정리 완료!':'과일을 모두 모았어요!',over:'다시 모아 볼까요?'}[s.status],400,245);g.font='16px system-ui';g.fillStyle='#ced6c9';g.fillText(`과일 ${s.collected}/12 · 점수 ${s.score} · 기회 ${s.lives}`,400,281)}}
function stop(){walk=0;keys={}}function pause(){if(state.status==='playing'){state.status='paused';stop()}else if(state.status==='paused')state.status='playing';sync()}
$('start').onclick=()=>{if(state.status==='clear')state=E.create(state.stage+1,state.score,state.lives);stop();E.start(state);sync()};$('pause').onclick=pause;$('restart').onclick=()=>{stop();state=E.create();sync()};$('left').onclick=()=>walk=walk===-1?0:-1;$('right').onclick=()=>walk=walk===1?0:1;$('stop').onclick=stop;$('up').onclick=()=>{if(E.climb(state,-1))walk=0;sync()};$('down').onclick=()=>{if(E.climb(state,1))walk=0;sync()};$('jump').onclick=()=>E.jump(state);
document.addEventListener('keydown',e=>{if(e.metaKey||e.ctrlKey||e.altKey)return;let k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s',' '].includes(k))e.preventDefault();if(['arrowleft','a'].includes(k)){keys.left=true;walk=0}if(['arrowright','d'].includes(k)){keys.right=true;walk=0}if(!e.repeat){if(['arrowup','w'].includes(k))E.climb(state,-1);if(['arrowdown','s'].includes(k))E.climb(state,1);if(k===' ')E.jump(state);if(k==='p')pause()}});document.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=false;if(['ArrowRight','d','D'].includes(e.key))keys.right=false});window.addEventListener('blur',()=>{stop();if(state.status==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();if(state.status==='playing')pause()}});
function frame(t){let dt=last?Math.min((t-last)/1000,.1):0;last=t;if(state.status==='playing'){acc+=dt;while(acc>=1/120){let lives=state.lives;E.step(state,1/120,{left:keys.left||walk===-1,right:keys.right||walk===1});if(state.lives<lives)stop();acc-=1/120}}else acc=0;sync();draw();requestAnimationFrame(frame)}sync();requestAnimationFrame(frame);
