const game=new Pinball(),c=document.querySelector('canvas'),ctx=c.getContext('2d'),$=id=>document.getElementById(id);let prev=performance.now();
function line(x1,y1,x2,y2,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function render(){ctx.clearRect(0,0,500,760);ctx.fillStyle='#182c3c';ctx.fillRect(0,0,500,760);for(let x=50;x<500;x+=40)for(let y=70;y<720;y+=40){ctx.fillStyle='#294253';ctx.beginPath();ctx.arc(x,y,1.1,0,7);ctx.fill();}
ctx.strokeStyle='#547380';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(26,554);ctx.lineTo(26,90);ctx.lineTo(92,35);ctx.lineTo(408,35);ctx.lineTo(474,90);ctx.lineTo(474,554);ctx.stroke();line(26,554,127,630,'#bd9470',9);line(474,554,373,630,'#bd9470',9);
ctx.fillStyle='#ddc69b';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText('L I T T L E   O R B I T',250,98);ctx.font='italic 28px Georgia';ctx.fillText('Make it bounce.',250,140);
for(const b of game.bumpers){ctx.fillStyle=b.flash?'#ffe3a0':'#c78356';ctx.shadowColor='#fac576';ctx.shadowBlur=b.flash?30:0;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#edd3a8';ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,b.r-7,0,7);ctx.stroke();ctx.fillStyle='#152c3c';ctx.font='bold 14px system-ui';ctx.fillText('100',b.x,b.y+5);}
ctx.strokeStyle='#314f60';ctx.lineWidth=1;ctx.beginPath();ctx.arc(250,320,155,0,7);ctx.stroke();
for(const f of game.flippers){line(f.x,f.y,f.x+Math.cos(f.a)*96,f.y+Math.sin(f.a)*96,'#edc785',16);ctx.fillStyle='#8e663f';ctx.beginPath();ctx.arc(f.x,f.y,5,0,7);ctx.fill();}
line(223,723,277,723,'#b46a58',3);ctx.fillStyle='#7e9aab';ctx.font='11px system-ui';ctx.fillText('D R A I N',250,743);
if(game.ball){const b=game.ball,g=ctx.createRadialGradient(b.x-3,b.y-4,1,b.x,b.y,10);g.addColorStop(0,'#fff');g.addColorStop(.5,'#d6e5e8');g.addColorStop(1,'#657c8a');ctx.fillStyle=g;ctx.beginPath();ctx.arc(b.x,b.y,9,0,7);ctx.fill();}
if(game.mode!=='playing'){ctx.fillStyle='#102333d9';ctx.fillRect(75,422,350,95);ctx.fillStyle='#f3d29b';ctx.font='bold 22px system-ui';ctx.fillText(game.mode==='paused'?'잠깐 쉬어 가기':game.mode==='over'?'이번 궤도는 여기까지':'다음 공을 올려 보세요',250,462);ctx.font='12px system-ui';ctx.fillText(game.mode==='paused'?'계속하기 버튼으로 돌아오세요':game.mode==='over'?'새 게임으로 다시 도전':'Space 또는 공 발사',250,492);}
$('score').textContent=game.score.toLocaleString();$('lives').textContent=game.lives;$('hits').textContent=game.hits;$('status').textContent=game.mode==='playing'?'공이 내려오면 타이밍을 맞춰 보세요.':game.mode==='ready'?'준비됐으면 공을 발사하세요.':game.mode==='paused'?'시간과 공이 함께 멈췄습니다.':'공 세 개를 모두 사용했습니다.';$('launch').disabled=game.mode!=='ready';$('power').disabled=game.mode==='playing'||game.mode==='paused';$('pause').disabled=game.mode==='ready'||game.mode==='over';$('pause').textContent=game.mode==='paused'?'계속하기':'일시정지';}
function frame(t){game.step((t-prev)/1000);prev=t;render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
$('launch').onclick=()=>game.launch();$('pause').onclick=()=>game.pause();$('reset').onclick=()=>{game.reset();game.power=Number($('power').value);};$('power').onchange=()=>game.power=Number($('power').value);
for(const side of ['left','right']){const el=$(side);el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);game.input[side]=true;};el.onpointerup=el.onpointercancel=el.onlostpointercapture=()=>game.input[side]=false;}
window.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT')return;const key=e.key.toLowerCase();if(['arrowleft','arrowright','a','d',' ','p','escape'].includes(key))e.preventDefault();if(key==='arrowleft'||key==='a')game.input.left=true;if(key==='arrowright'||key==='d')game.input.right=true;if(e.repeat)return;if(key===' ')game.launch();if(key==='p'||key==='escape')game.pause();});window.addEventListener('keyup',e=>{if(['arrowleft','a'].includes(e.key.toLowerCase()))game.input.left=false;if(['arrowright','d'].includes(e.key.toLowerCase()))game.input.right=false;});window.addEventListener('blur',()=>{game.release();if(game.mode==='playing')game.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.mode==='playing')game.pause();});
