const test=require('node:test'),assert=require('node:assert/strict');const{Pinball}=require('./engine');
function advance(g,t){for(let i=0;i<Math.round(t*480);i++)g.step(1/480);}
test('launch enters table above guide, reaches upper playfield',()=>{const g=new Pinball();g.launch();advance(g,.5);assert.equal(g.mode,'playing');assert.ok(g.ball.y<200);assert.equal(g.lives,3);});
test('launch cannot replace a live ball',()=>{const g=new Pinball();g.launch();advance(g,.1);const b={...g.ball};g.launch();assert.deepEqual(g.ball,b);});
test('pause freezes position, elapsed time and score',()=>{const g=new Pinball();g.launch();g.pause();const b={...g.ball},t=g.elapsed;advance(g,2);assert.deepEqual(g.ball,b);assert.equal(g.elapsed,t);g.pause();advance(g,.1);assert.notDeepEqual(g.ball,b);});
test('a bumper contact awards 100 once and pushes outward',()=>{const g=new Pinball();g.mode='playing';g.ball={x:178,y:185,vx:0,vy:300};advance(g,.015);assert.equal(g.score,100);assert.equal(g.hits,1);assert.ok(g.ball.vy<0);});
test('a drain consumes exactly one ball and preserves score',()=>{const g=new Pinball();g.score=200;g.mode='playing';g.ball={x:250,y:770,vx:0,vy:100};advance(g,2);assert.equal(g.lives,2);assert.equal(g.score,200);assert.equal(g.mode,'ready');});
test('three drains end the game and block launches',()=>{const g=new Pinball();for(let i=0;i<3;i++){g.launch();g.ball.y=780;advance(g,.01);}assert.equal(g.mode,'over');g.launch();assert.equal(g.ball,null);assert.equal(g.lives,0);});
test('left wall reflects rather than tunnels at high speed',()=>{const g=new Pinball();g.mode='playing';g.ball={x:50,y:430,vx:-1200,vy:0};advance(g,.04);assert.ok(g.ball.x>35);assert.ok(g.ball.vx>0);});
test('moving flipper sends ball upward; faster rotation changes impulse',()=>{const speeds=[];for(const power of [.55,1]){const g=new Pinball();g.mode='playing';g.power=power;g.ball={x:205,y:640,vx:0,vy:180};g.input.left=true;advance(g,.05);assert.ok(g.ball.vy<0);speeds.push(-g.ball.vy);}assert.ok(speeds[1]>speeds[0]);console.log('controlled comparison upward speed after 0.05s',speeds.map(Math.round));});
test('left and right flippers produce mirrored results',()=>{const gs=[new Pinball(),new Pinball()];for(let i=0;i<2;i++){const g=gs[i];g.mode='playing';g.ball={x:i?295:205,y:640,vx:0,vy:180};g.input[i?'right':'left']=true;advance(g,.05);}assert.ok(Math.abs(gs[0].ball.x+gs[1].ball.x-500)<1e-6);assert.ok(Math.abs(gs[0].ball.y-gs[1].ball.y)<1e-6);});
test('reset clears previous score, hits, ball and input',()=>{const g=new Pinball();g.launch();g.score=400;g.input.left=true;g.reset();assert.equal(g.score,0);assert.equal(g.hits,0);assert.equal(g.lives,3);assert.equal(g.ball,null);assert.equal(g.input.left,false);});
