'use strict';
const $=id=>document.getElementById(id),canvas=$('board'),c=canvas.getContext('2d'),game=new BubbleGarden.Game();const keys={left:false,right:false};let last=0,acc=0,ui='',walkUntil={left:0,right:0},clock=0;
function sync(){const s=[game.level,game.lives,game.score,game.popped,game.phase,game.paused,game.message].join('|');if(s===ui)return;ui=s;$('level').textContent=`${game.level+1} / 3`;$('lives').textContent='♥'.repeat(game.lives)||'0';$('count').textContent=game.popped+' / '+game.enemies.length;$('score').textContent=game.score;$('message').textContent=game.paused?'잠깐 쉬는 중 — 이어하기를 누르세요.':game.message;$('pause').textContent=game.paused?'이어하기':'일시정지';$('next').hidden=game.phase!=='won';$('next').textContent=game.level===2?'처음부터 다시':'다음 정원 →';for(const id of ['left','right','jump','fire','pop'])$(id).disabled=game.phase!=='playing'||game.paused;}
function clearInput(){keys.left=keys.right=false;walkUntil.left=walkUntil.right=0;}
function pause(){game.paused=!game.paused;clearInput();sync();}
$('pause').onclick=pause;$('retry').onclick=()=>{game.load(game.level);clearInput();sync();};$('next').onclick=()=>{game.load((game.level+1)%3);clearInput();sync();};$('jump').onclick=()=>game.jump();$('fire').onclick=()=>game.fire();$('pop').onclick=()=>{game.pop();sync();};
for(const id of ['left','right']){const b=$(id);let started=0;b.onpointerdown=e=>{started=performance.now();keys[id]=true;b.setPointerCapture(e.pointerId);};b.onpointerup=()=>{keys[id]=false;if(performance.now()-started<160)walkUntil[id]=clock+.16;};b.onpointercancel=()=>{keys[id]=false;walkUntil[id]=0;};b.onclick=e=>{if(e.detail===0)walkUntil[id]=clock+.18;};}
addEventListener('keydown',e=>{if(e.target.matches('button,input'))return;if(['ArrowLeft','ArrowRight','ArrowUp','Space'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft')keys.left=true;if(e.code==='ArrowRight')keys.right=true;if(e.repeat)return;if(e.code==='ArrowUp'||e.code==='Space')game.jump();if(e.code==='KeyZ')game.fire();if(e.code==='KeyX')game.pop();if(e.code==='KeyP')pause();});addEventListener('keyup',e=>{if(e.code==='ArrowLeft')keys.left=false;if(e.code==='ArrowRight')keys.right=false;});function blur(){clearInput();if(game.phase==='playing'){game.paused=true;sync();}}addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});
function circle(x,y,r,fill){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=fill;c.fill();}
function bubble(x,y,r,alpha=1){c.save();c.globalAlpha=alpha;circle(x,y,r,'rgba(148,224,224,.12)');c.strokeStyle='#a6dfed';c.lineWidth=2;c.stroke();c.beginPath();c.arc(x,y,r-5,3.5,4.8);c.strokeStyle='#fbe1f2';c.lineWidth=3;c.stroke();c.restore();}
function enemy(e){c.save();c.translate(e.x,e.y);circle(0,0,17,'#f3ae87');c.fillStyle='#e28b73';c.beginPath();c.moveTo(-15,-7);c.lineTo(-17,-24);c.lineTo(-3,-14);c.fill();c.beginPath();c.moveTo(15,-7);c.lineTo(17,-24);c.lineTo(3,-14);c.fill();circle(-6,-2,2.5,'#543552');circle(6,-2,2.5,'#543552');c.fillStyle='#543552';c.fillRect(-4,7,8,2);c.restore();}
function draw(t){const g=c.createLinearGradient(0,0,0,540);g.addColorStop(0,'#243455');g.addColorStop(1,'#354465');c.fillStyle=g;c.fillRect(0,0,960,540);for(let i=0;i<33;i++)circle(30+(i*131)%920,25+(i*67)%355,i%3?1.2:2,'#7c91b0');circle(810,90,39,'#f4dfb1');circle(826,78,34,'#243455');c.fillStyle='#2c3b5b';c.beginPath();c.moveTo(0,430);c.quadraticCurveTo(130,300,290,420);c.quadraticCurveTo(460,320,625,420);c.quadraticCurveTo(800,280,960,420);c.lineTo(960,480);c.lineTo(0,480);c.fill();
 for(const p of [{x:0,y:480,w:960},...BubbleGarden.levels[game.level].platforms]){c.fillStyle='#26374e';c.fillRect(p.x,p.y,p.w,16);c.fillStyle='#79bda8';c.fillRect(p.x,p.y,p.w,5);for(let x=p.x+14;x<p.x+p.w-5;x+=26){c.strokeStyle='#79bda8';c.lineWidth=2;c.beginPath();c.moveTo(x,p.y);c.lineTo(x-4,p.y-7);c.moveTo(x,p.y);c.lineTo(x+4,p.y-5);c.stroke();}}
 c.fillStyle='#a3b4c8';c.font='12px system-ui';c.fillText(BubbleGarden.levels[game.level].name,25,518);c.textAlign='right';c.fillText('가둔 방울 가까이에서 X',935,518);c.textAlign='left';
 for(const e of game.enemies){if(e.state==='gone')continue;enemy(e);if(e.state==='trapped'){bubble(e.x,e.y,28);c.fillStyle=e.timer<2?'#ffb4c6':'#defff0';c.font='bold 14px system-ui';c.textAlign='center';c.fillText(Math.ceil(e.timer)+'s',e.x,e.y-36);c.textAlign='left';}}
 for(const b of game.bubbles)bubble(b.x,b.y,19,Math.min(1,(3-b.age)*2));
 const p=game.player;c.save();c.globalAlpha=p.invuln>0&&Math.floor(t/100)%2?.35:1;circle(p.x,p.y,20,'#c0efda');circle(p.x-9,p.y+16,6,'#89bea9');circle(p.x+9,p.y+16,6,'#89bea9');circle(p.x-6+p.face*3,p.y-3,2.5,'#254c49');circle(p.x+6+p.face*3,p.y-3,2.5,'#254c49');circle(p.x+p.face*12,p.y+5,3,'#f3adc2');c.fillStyle='#f3adc2';c.fillRect(p.x-16,p.y-22,32,5);c.restore();
 for(const f of game.effects){for(let i=0;i<8;i++){const a=i*Math.PI/4;circle(f.x+Math.cos(a)*f.age*100,f.y+Math.sin(a)*f.age*100,4*(1-f.age/.6),'#ffe3b3');}}
 if(game.paused||game.phase!=='playing'){c.fillStyle='rgba(19,29,50,.85)';c.fillRect(235,172,490,142);c.textAlign='center';c.fillStyle='#e7f4e9';c.font='bold 29px system-ui';c.fillText(game.paused?'잠깐 쉬어가기':game.phase==='won'?'정원이 조용해졌어요':'한 번 더 해볼까요?',480,225);c.fillStyle='#b4c6d4';c.font='15px system-ui';c.fillText(game.paused?'이어하기 버튼으로 계속':game.phase==='won'?`터뜨린 방울 ${game.popped}개 · ${game.score}점`:'이 판 다시 버튼으로 재도전',480,265);c.textAlign='left';}}
function frame(t){if(!last)last=t;acc+=Math.min(t-last,50)/1000;last=t;while(acc>=BubbleGarden.DT){clock+=BubbleGarden.DT;game.step({left:keys.left||clock<walkUntil.left,right:keys.right||clock<walkUntil.right});acc-=BubbleGarden.DT;}sync();draw(t);requestAnimationFrame(frame);}sync();requestAnimationFrame(frame);
